/**
 * @registry
 * name: Product Variant Picker
 * category: Forms
 * style: Minimal
 * tags: recent
 * description: Sélecteur de couleur et taille produit avec stock et combinaison indisponible.
 * prompt: Create a responsive product variant picker with accessible color swatches, size options, unavailable combinations, stock message, quantity and add-to-cart action.
 */
'use client';
import { Minus, Plus, ShoppingBag } from 'lucide-react';
import { useState } from 'react';
const colors=[['Sand','#d6b98c'],['Forest','#315c45'],['Night','#242633']] as const;
export function ProductVariantPicker(){const[color,setColor]=useState('Sand');const[size,setSize]=useState('M');const[qty,setQty]=useState(1);const unavailable=color==='Forest'?'XL':'XS';return <section className="w-full max-w-md rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950 sm:p-6"><p className="text-xs font-bold uppercase tracking-widest text-zinc-400">Performance collection</p><h2 className="mt-2 text-2xl font-bold text-zinc-950 dark:text-white">Motion Shell Jacket</h2><p className="mt-1 text-lg font-semibold text-zinc-900 dark:text-white">$128</p><fieldset className="mt-6"><legend className="text-sm font-semibold text-zinc-900 dark:text-white">Color: <span className="font-normal text-zinc-500">{color}</span></legend><div className="mt-3 flex gap-3">{colors.map(([name,value])=><button key={name} type="button" onClick={()=>setColor(name)} aria-label={name} aria-pressed={color===name} className={`size-9 rounded-full border-4 border-white shadow-[0_0_0_1px_#d4d4d8] ${color===name?'ring-2 ring-zinc-950 ring-offset-2 dark:ring-white dark:ring-offset-zinc-950':''}`} style={{backgroundColor:value}}/>)}</div></fieldset><fieldset className="mt-6"><legend className="text-sm font-semibold text-zinc-900 dark:text-white">Size</legend><div className="mt-3 grid grid-cols-4 gap-2">{['XS','S','M','L','XL'].map((item)=><button key={item} type="button" disabled={item===unavailable} onClick={()=>setSize(item)} aria-pressed={size===item} className={`rounded-xl border py-2.5 text-sm font-medium disabled:cursor-not-allowed disabled:bg-zinc-100 disabled:text-zinc-300 dark:disabled:bg-zinc-900 ${size===item?'border-zinc-950 bg-zinc-950 text-white dark:border-white dark:bg-white dark:text-zinc-950':'border-zinc-200 text-zinc-700 dark:border-zinc-800 dark:text-zinc-300'}`}>{item}</button>)}</div></fieldset><p className="mt-4 text-xs text-emerald-600">In stock · ships within 24 hours</p><div className="mt-5 flex gap-3"><div className="flex items-center rounded-xl border border-zinc-200 dark:border-zinc-800"><button onClick={()=>setQty(Math.max(1,qty-1))} aria-label="Decrease quantity" className="p-3"><Minus size={15}/></button><span className="w-6 text-center text-sm">{qty}</span><button onClick={()=>setQty(Math.min(9,qty+1))} aria-label="Increase quantity" className="p-3"><Plus size={15}/></button></div><button className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-600 text-sm font-bold text-white"><ShoppingBag size={17}/>Add · ${128*qty}</button></div></section>}
