/**
 * @registry
 * name: Quick Apply Form
 * category: Forms
 * style: Minimal
 * tags: recent
 * description: Formulaire de candidature rapide avec CV, profil et validation.
 * prompt: Create a responsive quick job application form with name, email, portfolio URL, simulated resume upload, consent checkbox, validation and a success state.
 */
'use client';
import { CheckCircle2, FileText, Upload } from 'lucide-react';import { useState,type FormEvent } from 'react';
export function QuickApplyForm(){const[file,setFile]=useState('');const[consent,setConsent]=useState(false);const[done,setDone]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();if(file&&consent)setDone(true)};if(done)return <section className="w-full max-w-md rounded-3xl border border-emerald-200 bg-white p-8 text-center dark:border-emerald-500/20 dark:bg-zinc-950"><CheckCircle2 className="mx-auto size-12 text-emerald-500"/><h2 className="mt-4 text-xl font-bold text-zinc-950 dark:text-white">Application sent</h2><p className="mt-2 text-sm text-zinc-500">Northstar Labs received your profile.</p><button onClick={()=>setDone(false)} className="mt-5 text-sm font-semibold text-blue-600">Back to form</button></section>;return <form onSubmit={submit} className="w-full max-w-md space-y-4 rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950 sm:p-6"><div><h2 className="text-lg font-bold text-zinc-950 dark:text-white">Quick apply</h2><p className="text-sm text-zinc-500">Senior Product Designer</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium text-zinc-600 dark:text-zinc-300">Full name<input required className="mt-1.5 w-full rounded-xl border border-zinc-300 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-blue-500 dark:border-zinc-700"/></label><label className="text-xs font-medium text-zinc-600 dark:text-zinc-300">Email<input required type="email" className="mt-1.5 w-full rounded-xl border border-zinc-300 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-blue-500 dark:border-zinc-700"/></label></div><label className="block text-xs font-medium text-zinc-600 dark:text-zinc-300">Portfolio URL<input type="url" placeholder="https://" className="mt-1.5 w-full rounded-xl border border-zinc-300 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-blue-500 dark:border-zinc-700"/></label><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-zinc-300 p-4 dark:border-zinc-700"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10">{file?<FileText size={18}/>:<Upload size={18}/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-zinc-900 dark:text-white">{file||'Upload your resume'}</span><span className="text-xs text-zinc-500">PDF or DOCX · max 5 MB</span></span><input type="file" accept=".pdf,.doc,.docx" className="sr-only" onChange={e=>setFile(e.target.files?.[0]?.name||'')}/></label><label className="flex items-start gap-2 text-xs text-zinc-500"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-0.5 accent-blue-600"/>I agree to share my profile with this employer.</label><button disabled={!file||!consent} className="w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-40">Submit application</button></form>}
