/**
 * @registry
 * name: Order Success Card
 * category: CTA
 * style: Gradient
 * tags: recent
 * description: Confirmation de commande avec numéro copiable, suivi et prochaines étapes.
 * prompt: Create a responsive order success card with animated success mark, copyable order number, delivery estimate, progress steps and track-order and continue-shopping actions.
 */
'use client';
import { Check, Copy, PackageCheck } from 'lucide-react';import { useState } from 'react';
export function OrderSuccessCard(){const[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard?.writeText('PU-48291');setCopied(true);window.setTimeout(()=>setCopied(false),1500)};return <section className="w-full max-w-lg overflow-hidden rounded-[2rem] border border-emerald-200 bg-white text-center shadow-2xl shadow-emerald-500/10 dark:border-emerald-500/20 dark:bg-zinc-950"><div className="bg-gradient-to-br from-emerald-500 to-cyan-500 px-6 py-8 text-white"><div className="mx-auto grid size-16 place-items-center rounded-full bg-white/20 ring-8 ring-white/10 motion-safe:animate-pulse"><Check size={30}/></div><h2 className="mt-4 text-2xl font-bold">Order confirmed!</h2><p className="mt-1 text-sm text-emerald-50">We’re preparing your package.</p></div><div className="p-5 sm:p-6"><button onClick={copy} className="mx-auto flex items-center gap-2 rounded-full bg-zinc-100 px-4 py-2 text-sm text-zinc-700 dark:bg-zinc-900 dark:text-zinc-300"><span>Order <strong>#PU-48291</strong></span>{copied?<Check size={14} className="text-emerald-500"/>:<Copy size={14}/>}</button><div className="mt-6 flex items-center justify-between text-left"><div><p className="text-xs text-zinc-500">Estimated delivery</p><p className="font-semibold text-zinc-950 dark:text-white">October 16–18</p></div><PackageCheck size={28} className="text-emerald-500"/></div><div className="mt-5 flex items-center"><span className="size-3 rounded-full bg-emerald-500"/><span className="h-1 flex-1 bg-emerald-500"/><span className="size-3 rounded-full bg-emerald-500"/><span className="h-1 flex-1 bg-zinc-200 dark:bg-zinc-800"/><span className="size-3 rounded-full bg-zinc-200 dark:bg-zinc-800"/></div><div className="mt-2 flex justify-between text-[10px] text-zinc-500"><span>Confirmed</span><span>Preparing</span><span>Delivered</span></div><div className="mt-6 grid gap-2 sm:grid-cols-2"><button className="rounded-xl bg-zinc-950 py-3 text-sm font-bold text-white dark:bg-white dark:text-zinc-950">Track order</button><button className="rounded-xl border border-zinc-200 py-3 text-sm font-semibold text-zinc-700 dark:border-zinc-800 dark:text-zinc-300">Continue shopping</button></div></div></section>}
