// Generated by scripts/sync-registry.mjs. Do not edit by hand.
import type { ComponentType } from 'react';
import { AgentPlanChecklist } from './ai-chat/AgentPlanChecklist';
import { AgentTrace } from './ai-chat/AgentTrace';
import { AiSummaryCard } from './ai-chat/AiSummaryCard';
import { AnswerFeedbackForm } from './ai-chat/AnswerFeedbackForm';
import { ArtifactPanel } from './ai-chat/ArtifactPanel';
import { AttachmentComposer } from './ai-chat/AttachmentComposer';
import { ChatBubbleStatus } from './ai-chat/ChatBubbleStatus';
import { ChatHistoryList } from './ai-chat/ChatHistoryList';
import { ChatModeComposer } from './ai-chat/ChatModeComposer';
import { ChatThread } from './ai-chat/ChatThread';
import { ClarifyingQuestionnaire } from './ai-chat/ClarifyingQuestionnaire';
import { CodeAnswer } from './ai-chat/CodeAnswer';
import { ContextFilesPanel } from './ai-chat/ContextFilesPanel';
import { ContextMeter } from './ai-chat/ContextMeter';
import { DiffSuggestionCard } from './ai-chat/DiffSuggestionCard';
import { ImageGeneration } from './ai-chat/ImageGeneration';
import { MemoryChipsPanel } from './ai-chat/MemoryChipsPanel';
import { MessageActions } from './ai-chat/MessageActions';
import { ModelSelector } from './ai-chat/ModelSelector';
import { PromptInputBar } from './ai-chat/PromptInputBar';
import { PromptLibraryPicker } from './ai-chat/PromptLibraryPicker';
import { ResponseVariants } from './ai-chat/ResponseVariants';
import { SlashCommandMenu } from './ai-chat/SlashCommandMenu';
import { SourcesAnswer } from './ai-chat/SourcesAnswer';
import { StreamingMessage } from './ai-chat/StreamingMessage';
import { SuggestedPrompts } from './ai-chat/SuggestedPrompts';
import { SupportWidget } from './ai-chat/SupportWidget';
import { ThinkingAccordion } from './ai-chat/ThinkingAccordion';
import { ToneRewriteBox } from './ai-chat/ToneRewriteBox';
import { ToolCallCard } from './ai-chat/ToolCallCard';
import { TypingIndicator } from './ai-chat/TypingIndicator';
import { VoiceOrb } from './ai-chat/VoiceOrb';
import { VoiceRecorderInput } from './ai-chat/VoiceRecorderInput';
import { BugTriageBoard } from './boards/BugTriageBoard';
import { CandidatePipelineBoard } from './boards/CandidatePipelineBoard';
import { ContentCalendar } from './boards/ContentCalendar';
import { ContentPipelineBoard } from './boards/ContentPipelineBoard';
import { CustomerJourneyBoard } from './boards/CustomerJourneyBoard';
import { DragDropKanban } from './boards/DragDropKanban';
import { EisenhowerMatrix } from './boards/EisenhowerMatrix';
import { FeatureVotingBoard } from './boards/FeatureVotingBoard';
import { GanttTimeline } from './boards/GanttTimeline';
import { GroupedIssueList } from './boards/GroupedIssueList';
import { HabitTrackerBoard } from './boards/HabitTrackerBoard';
import { HiringPipeline } from './boards/HiringPipeline';
import { InlineAddBoard } from './boards/InlineAddBoard';
import { IssueCardDetail } from './boards/IssueCardDetail';
import { MilestoneTracker } from './boards/MilestoneTracker';
import { MoodBoard } from './boards/MoodBoard';
import { NowNextLaterRoadmap } from './boards/NowNextLaterRoadmap';
import { OkrBoard } from './boards/OkrBoard';
import { PlanningPokerBoard } from './boards/PlanningPokerBoard';
import { ReleaseTrainBoard } from './boards/ReleaseTrainBoard';
import { RetroBoard } from './boards/RetroBoard';
import { SalesPipeline } from './boards/SalesPipeline';
import { SprintBurndownBoard } from './boards/SprintBurndownBoard';
import { StickyNotesWall } from './boards/StickyNotesWall';
import { SwimlaneBoard } from './boards/SwimlaneBoard';
import { TimeBlockPlanner } from './boards/TimeBlockPlanner';
import { UserStoryMap } from './boards/UserStoryMap';
import { WipLimitBoard } from './boards/WipLimitBoard';
import { AvatarButton } from './buttons/AvatarButton';
import { BadgeCountButton } from './buttons/BadgeCountButton';
import { BarrelRollNavigation } from './buttons/BarrelRollNavigation';
import { BorderBeamButton } from './buttons/BorderBeamButton';
import { ButtonGroup } from './buttons/ButtonGroup';
import { ButtonVariants } from './buttons/ButtonVariants';
import { CircleRevealButton } from './buttons/CircleRevealButton';
import { ConfettiButton } from './buttons/ConfettiButton';
import { CoolModeButton } from './buttons/CoolModeButton';
import { CopyLinkButton } from './buttons/CopyLinkButton';
import { DownloadProgressButton } from './buttons/DownloadProgressButton';
import { ElasticPressButton } from './buttons/ElasticPressButton';
import { ElasticSendButton } from './buttons/ElasticSendButton';
import { ExpandIconButton } from './buttons/ExpandIconButton';
import { FlipButton3D } from './buttons/FlipButton3D';
import { FloatingActionButton } from './buttons/FloatingActionButton';
import { GlitchButton } from './buttons/GlitchButton';
import { GradientOutlineButton } from './buttons/GradientOutlineButton';
import { HoldToConfirmButton } from './buttons/HoldToConfirmButton';
import { InteractiveHoverButton } from './buttons/InteractiveHoverButton';
import { KbdShortcutButton } from './buttons/KbdShortcutButton';
import { LikeBurstButton } from './buttons/LikeBurstButton';
import { MagneticPullButton } from './buttons/MagneticPullButton';
import { NeonButton } from './buttons/NeonButton';
import { PulsatingButton } from './buttons/PulsatingButton';
import { PushButton } from './buttons/PushButton';
import { RainbowButton } from './buttons/RainbowButton';
import { ResendCodeButton } from './buttons/ResendCodeButton';
import { RippleButton } from './buttons/RippleButton';
import { ShimmerButton } from './buttons/ShimmerButton';
import { ShinyButton } from './buttons/ShinyButton';
import { SkeuomorphicButton } from './buttons/SkeuomorphicButton';
import { SlideArrowButton } from './buttons/SlideArrowButton';
import { SocialLoginButtons } from './buttons/SocialLoginButtons';
import { SplitButton } from './buttons/SplitButton';
import { SwipeToConfirm } from './buttons/SwipeToConfirm';
import { AnimatedBeamCard } from './cards/AnimatedBeamCard';
import { AnimatedNotificationList } from './cards/AnimatedNotificationList';
import { BentoFeatures } from './cards/BentoFeatures';
import { BlogPostCard } from './cards/BlogPostCard';
import { BookCoverCard } from './cards/BookCoverCard';
import { CarouselCard } from './cards/CarouselCard';
import { CodeComparison } from './cards/CodeComparison';
import { CollectibleCard } from './cards/CollectibleCard';
import { CourseCard } from './cards/CourseCard';
import { EventTicketCard } from './cards/EventTicketCard';
import { ExpandableStatCard } from './cards/ExpandableStatCard';
import { FocusTimerCard } from './cards/FocusTimerCard';
import { GlareHoverCard } from './cards/GlareHoverCard';
import { HolographicEventPass } from './cards/HolographicEventPass';
import { HoverGalleryCard } from './cards/HoverGalleryCard';
import { InteractiveProductInspector } from './cards/InteractiveProductInspector';
import { InvoicePreviewCard } from './cards/InvoicePreviewCard';
import { JobOpportunityCard } from './cards/JobOpportunityCard';
import { LayeredProjectCard } from './cards/LayeredProjectCard';
import { LensCard } from './cards/LensCard';
import { MaskShapesCard } from './cards/MaskShapesCard';
import { MusicPlayerCard } from './cards/MusicPlayerCard';
import { NeonGradientCard } from './cards/NeonGradientCard';
import { OrbitingCircles } from './cards/OrbitingCircles';
import { PodcastEpisodeCard } from './cards/PodcastEpisodeCard';
import { ProfileCoverCard } from './cards/ProfileCoverCard';
import { PropertyListingCard } from './cards/PropertyListingCard';
import { RecipeCard } from './cards/RecipeCard';
import { RepoCard } from './cards/RepoCard';
import { SafariMockup } from './cards/SafariMockup';
import { SellerTrustCard } from './cards/SellerTrustCard';
import { ShineBorderCard } from './cards/ShineBorderCard';
import { SpecialistPicker } from './cards/SpecialistPicker';
import { SpotlightCard } from './cards/SpotlightCard';
import { StatCard } from './cards/StatCard';
import { TeamMemberCard } from './cards/TeamMemberCard';
import { TweetCard } from './cards/TweetCard';
import { AreaRangeChart } from './charts/AreaRangeChart';
import { BoxPlotChart } from './charts/BoxPlotChart';
import { BubbleChart } from './charts/BubbleChart';
import { BulletChart } from './charts/BulletChart';
import { CandlestickChart } from './charts/CandlestickChart';
import { DivergingBarChart } from './charts/DivergingBarChart';
import { DotPlotChart } from './charts/DotPlotChart';
import { ForecastLineChart } from './charts/ForecastLineChart';
import { GaugeChart } from './charts/GaugeChart';
import { GroupedBarChart } from './charts/GroupedBarChart';
import { InteractiveBarChart } from './charts/InteractiveBarChart';
import { InteractiveDonutChart } from './charts/InteractiveDonutChart';
import { LollipopChart } from './charts/LollipopChart';
import { ParetoChart } from './charts/ParetoChart';
import { PercentStackedBar } from './charts/PercentStackedBar';
import { PolarAreaChart } from './charts/PolarAreaChart';
import { PunchCardChart } from './charts/PunchCardChart';
import { RadarChart } from './charts/RadarChart';
import { RadialBarChart } from './charts/RadialBarChart';
import { RadialProgressStats } from './charts/RadialProgressStats';
import { RangeBandChart } from './charts/RangeBandChart';
import { ScatterPlot } from './charts/ScatterPlot';
import { SlopeChart } from './charts/SlopeChart';
import { StackedAreaChart } from './charts/StackedAreaChart';
import { StepLineChart } from './charts/StepLineChart';
import { StreamgraphChart } from './charts/StreamgraphChart';
import { SunburstChart } from './charts/SunburstChart';
import { TreemapChart } from './charts/TreemapChart';
import { WaterfallChart } from './charts/WaterfallChart';
import { AddOnCheckboxes } from './checkboxes/AddOnCheckboxes';
import { AllergenCheckboxes } from './checkboxes/AllergenCheckboxes';
import { AnimatedChecklist } from './checkboxes/AnimatedChecklist';
import { CheckboxCards } from './checkboxes/CheckboxCards';
import { CheckboxGroupDescribed } from './checkboxes/CheckboxGroupDescribed';
import { ChipCheckboxes } from './checkboxes/ChipCheckboxes';
import { CircleCheckbox } from './checkboxes/CircleCheckbox';
import { ColorSwatchCheckboxes } from './checkboxes/ColorSwatchCheckboxes';
import { FacetCountCheckboxes } from './checkboxes/FacetCountCheckboxes';
import { GoalCardCheckboxes } from './checkboxes/GoalCardCheckboxes';
import { GroceryChecklist } from './checkboxes/GroceryChecklist';
import { HeartCheckbox } from './checkboxes/HeartCheckbox';
import { ImagePickerCheckbox } from './checkboxes/ImagePickerCheckbox';
import { IndeterminateTree } from './checkboxes/IndeterminateTree';
import { InterestChips } from './checkboxes/InterestChips';
import { JellyCheckbox } from './checkboxes/JellyCheckbox';
import { NeonCheckbox } from './checkboxes/NeonCheckbox';
import { PermissionsMatrix } from './checkboxes/PermissionsMatrix';
import { RangeSelectList } from './checkboxes/RangeSelectList';
import { RetroCheckbox } from './checkboxes/RetroCheckbox';
import { SelectAllCards } from './checkboxes/SelectAllCards';
import { SizeCheckboxGrid } from './checkboxes/SizeCheckboxGrid';
import { SvgDrawCheckbox } from './checkboxes/SvgDrawCheckbox';
import { SwapIconCheckbox } from './checkboxes/SwapIconCheckbox';
import { TermsConsentForm } from './checkboxes/TermsConsentForm';
import { ValidatedCheckbox } from './checkboxes/ValidatedCheckbox';
import { WeekdayPicker } from './checkboxes/WeekdayPicker';
import { BeforeAfterSliderCta } from './cta/BeforeAfterSliderCta';
import { BookDemoCta } from './cta/BookDemoCta';
import { CommunityJoinCta } from './cta/CommunityJoinCta';
import { ContactSalesCta } from './cta/ContactSalesCta';
import { DecisionPathCta } from './cta/DecisionPathCta';
import { DownloadAppsCta } from './cta/DownloadAppsCta';
import { EarlyAccessCodeCta } from './cta/EarlyAccessCodeCta';
import { ExitIntentCta } from './cta/ExitIntentCta';
import { GradientShapesCta } from './cta/GradientShapesCta';
import { InlineBannerCta } from './cta/InlineBannerCta';
import { InlineNewsletterCta } from './cta/InlineNewsletterCta';
import { OrderSuccessCard } from './cta/OrderSuccessCard';
import { PricingTeaserCta } from './cta/PricingTeaserCta';
import { QuizCta } from './cta/QuizCta';
import { RatingFeedbackCta } from './cta/RatingFeedbackCta';
import { ReferralCta } from './cta/ReferralCta';
import { SplitImageCta } from './cta/SplitImageCta';
import { SpotlightCta } from './cta/SpotlightCta';
import { StatsCta } from './cta/StatsCta';
import { StickyMobileCta } from './cta/StickyMobileCta';
import { TestimonialCta } from './cta/TestimonialCta';
import { TrialChecklistCta } from './cta/TrialChecklistCta';
import { TrialExpiryCta } from './cta/TrialExpiryCta';
import { VideoDemoCta } from './cta/VideoDemoCta';
import { WebinarCta } from './cta/WebinarCta';
import { ActivityFeed } from './dashboard/ActivityFeed';
import { ApplicationTracker } from './dashboard/ApplicationTracker';
import { AppointmentManager } from './dashboard/AppointmentManager';
import { AppointmentsToday } from './dashboard/AppointmentsToday';
import { BillingSummary } from './dashboard/BillingSummary';
import { CampaignStatsWidget } from './dashboard/CampaignStatsWidget';
import { CashflowWidget } from './dashboard/CashflowWidget';
import { ContributionHeatmap } from './dashboard/ContributionHeatmap';
import { ConversionBreakdown } from './dashboard/ConversionBreakdown';
import { CryptoPortfolio } from './dashboard/CryptoPortfolio';
import { DarkMetricPanel } from './dashboard/DarkMetricPanel';
import { DeploymentsWidget } from './dashboard/DeploymentsWidget';
import { ExpenseCategoriesWidget } from './dashboard/ExpenseCategoriesWidget';
import { GoalGauge } from './dashboard/GoalGauge';
import { HorizontalTimeline } from './dashboard/HorizontalTimeline';
import { InventoryAlertsWidget } from './dashboard/InventoryAlertsWidget';
import { KpiGrid } from './dashboard/KpiGrid';
import { MatchdayScoreboard } from './dashboard/MatchdayScoreboard';
import { ProjectProgressList } from './dashboard/ProjectProgressList';
import { QuickNotesWidget } from './dashboard/QuickNotesWidget';
import { RealtimeVisitors } from './dashboard/RealtimeVisitors';
import { RecentSales } from './dashboard/RecentSales';
import { ResizablePanels } from './dashboard/ResizablePanels';
import { RevenueOverview } from './dashboard/RevenueOverview';
import { ServerHealthPanel } from './dashboard/ServerHealthPanel';
import { ServiceUptime } from './dashboard/ServiceUptime';
import { SetupStepsWidget } from './dashboard/SetupStepsWidget';
import { StatGroup } from './dashboard/StatGroup';
import { StorageUsage } from './dashboard/StorageUsage';
import { SupportSlaWidget } from './dashboard/SupportSlaWidget';
import { TasksWidget } from './dashboard/TasksWidget';
import { TeamPresenceWidget } from './dashboard/TeamPresenceWidget';
import { TeamWorkload } from './dashboard/TeamWorkload';
import { TopCountries } from './dashboard/TopCountries';
import { UpcomingEvents } from './dashboard/UpcomingEvents';
import { WeatherWidget } from './dashboard/WeatherWidget';
import { WelcomeBanner } from './dashboard/WelcomeBanner';
import { AccordionSitemapFooter } from './footer/AccordionSitemapFooter';
import { AppDownloadFooter } from './footer/AppDownloadFooter';
import { BackToTopFooter } from './footer/BackToTopFooter';
import { ChangelogFooter } from './footer/ChangelogFooter';
import { ColumnsNewsletterFooter } from './footer/ColumnsNewsletterFooter';
import { CommunityFooter } from './footer/CommunityFooter';
import { ContactFormFooter } from './footer/ContactFormFooter';
import { ContactInfoFooter } from './footer/ContactInfoFooter';
import { CtaBandFooter } from './footer/CtaBandFooter';
import { DocsPagerFooter } from './footer/DocsPagerFooter';
import { EcommerceTrustFooter } from './footer/EcommerceTrustFooter';
import { FloatingCardFooter } from './footer/FloatingCardFooter';
import { GradientBrandFooter } from './footer/GradientBrandFooter';
import { LegalBarFooter } from './footer/LegalBarFooter';
import { MagazineFooter } from './footer/MagazineFooter';
import { MarqueeFooter } from './footer/MarqueeFooter';
import { MegaLinksFooter } from './footer/MegaLinksFooter';
import { MinimalCenteredFooter } from './footer/MinimalCenteredFooter';
import { OfficesFooter } from './footer/OfficesFooter';
import { PartnersFooter } from './footer/PartnersFooter';
import { PortfolioFooter } from './footer/PortfolioFooter';
import { PreferencesFooter } from './footer/PreferencesFooter';
import { SocialWallFooter } from './footer/SocialWallFooter';
import { StartupBadgesFooter } from './footer/StartupBadgesFooter';
import { StatusFooter } from './footer/StatusFooter';
import { WaveFooter } from './footer/WaveFooter';
import { WordmarkFooter } from './footer/WordmarkFooter';
import { AddressFieldset } from './forms/AddressFieldset';
import { AuctionBidPanel } from './forms/AuctionBidPanel';
import { AutocompleteInput } from './forms/AutocompleteInput';
import { AvailabilitySlotPicker } from './forms/AvailabilitySlotPicker';
import { AvatarUploader } from './forms/AvatarUploader';
import { ChangePasswordForm } from './forms/ChangePasswordForm';
import { ColorPickerInput } from './forms/ColorPickerInput';
import { CreditCardForm } from './forms/CreditCardForm';
import { CurrencyConverterForm } from './forms/CurrencyConverterForm';
import { DateRangeCalendar } from './forms/DateRangeCalendar';
import { DualRangeSlider } from './forms/DualRangeSlider';
import { EventRsvpForm } from './forms/EventRsvpForm';
import { FeedbackForm } from './forms/FeedbackForm';
import { FileDropzone } from './forms/FileDropzone';
import { FloatingLabelInput } from './forms/FloatingLabelInput';
import { ForgotPassword } from './forms/ForgotPassword';
import { InlineDatePicker } from './forms/InlineDatePicker';
import { InlineEditField } from './forms/InlineEditField';
import { InputGroupShowcase } from './forms/InputGroupShowcase';
import { MarkedRangeSlider } from './forms/MarkedRangeSlider';
import { MultiSelectCombobox } from './forms/MultiSelectCombobox';
import { NewsletterTopicsForm } from './forms/NewsletterTopicsForm';
import { NpsSurvey } from './forms/NpsSurvey';
import { NumberStepperInput } from './forms/NumberStepperInput';
import { OtpInput } from './forms/OtpInput';
import { PasswordStrength } from './forms/PasswordStrength';
import { PhoneInput } from './forms/PhoneInput';
import { ProductVariantPicker } from './forms/ProductVariantPicker';
import { QuickApplyForm } from './forms/QuickApplyForm';
import { RatingMatrixForm } from './forms/RatingMatrixForm';
import { ReservationForm } from './forms/ReservationForm';
import { ShippingMethodSelector } from './forms/ShippingMethodSelector';
import { SignInForm } from './forms/SignInForm';
import { SignaturePad } from './forms/SignaturePad';
import { StarRatingInput } from './forms/StarRatingInput';
import { TagInput } from './forms/TagInput';
import { TimeFieldInput } from './forms/TimeFieldInput';
import { TransferList } from './forms/TransferList';
import { TypedSignatureField } from './forms/TypedSignatureField';
import { ValidatedContactForm } from './forms/ValidatedContactForm';
import { VoiceNoteComposer } from './forms/VoiceNoteComposer';
import { WizardForm } from './forms/WizardForm';
import { AgencyShowcaseHero } from './hero/AgencyShowcaseHero';
import { AuroraBlobHero } from './hero/AuroraBlobHero';
import { BeamSpotlightHero } from './hero/BeamSpotlightHero';
import { BigGradientHero } from './hero/BigGradientHero';
import { ChecklistHero } from './hero/ChecklistHero';
import { CodeEditorHero } from './hero/CodeEditorHero';
import { CountdownHero } from './hero/CountdownHero';
import { EditorialHero } from './hero/EditorialHero';
import { FloatingCardsHero } from './hero/FloatingCardsHero';
import { GlobeHero } from './hero/GlobeHero';
import { GradientMeshHero } from './hero/GradientMeshHero';
import { GridGlowHero } from './hero/GridGlowHero';
import { Hover3DHero } from './hero/Hover3DHero';
import { IconCloudHero } from './hero/IconCloudHero';
import { LaunchBadgeHero } from './hero/LaunchBadgeHero';
import { LogoCloudHero } from './hero/LogoCloudHero';
import { MapPinsHero } from './hero/MapPinsHero';
import { MetricsHero } from './hero/MetricsHero';
import { OverlayImageHero } from './hero/OverlayImageHero';
import { PersonaTabsHero } from './hero/PersonaTabsHero';
import { PhoneMockupHero } from './hero/PhoneMockupHero';
import { ScanlineLaunchHero } from './hero/ScanlineLaunchHero';
import { SearchHero } from './hero/SearchHero';
import { SocialProofHero } from './hero/SocialProofHero';
import { SplitMockupHero } from './hero/SplitMockupHero';
import { StatsTickerHero } from './hero/StatsTickerHero';
import { TerminalHero } from './hero/TerminalHero';
import { TiltedScreensHero } from './hero/TiltedScreensHero';
import { TypewriterHero } from './hero/TypewriterHero';
import { VideoPreviewHero } from './hero/VideoPreviewHero';
import { WaitlistHero } from './hero/WaitlistHero';
import { BatteryChargeLoader } from './loader/BatteryChargeLoader';
import { BouncingBallLoader } from './loader/BouncingBallLoader';
import { BouncingDots } from './loader/BouncingDots';
import { ChatSkeletonLoader } from './loader/ChatSkeletonLoader';
import { CircularProgress } from './loader/CircularProgress';
import { ClockLoader } from './loader/ClockLoader';
import { CubeGrid } from './loader/CubeGrid';
import { DnaHelixLoader } from './loader/DnaHelixLoader';
import { EqualizerBars } from './loader/EqualizerBars';
import { FlippingSquare } from './loader/FlippingSquare';
import { GradientRingSpinner } from './loader/GradientRingSpinner';
import { HourglassLoader } from './loader/HourglassLoader';
import { IndeterminateBar } from './loader/IndeterminateBar';
import { InfinityLoader } from './loader/InfinityLoader';
import { LetterWave } from './loader/LetterWave';
import { LoadingButton } from './loader/LoadingButton';
import { LoadingVariants } from './loader/LoadingVariants';
import { MorphShapeLoader } from './loader/MorphShapeLoader';
import { OrbitDotsLoader } from './loader/OrbitDotsLoader';
import { PendulumLoader } from './loader/PendulumLoader';
import { PercentCounterLoader } from './loader/PercentCounterLoader';
import { PulseRings } from './loader/PulseRings';
import { RadarScanLoader } from './loader/RadarScanLoader';
import { SegmentSpinner } from './loader/SegmentSpinner';
import { ShimmerImageGrid } from './loader/ShimmerImageGrid';
import { SignalConstellationLoader } from './loader/SignalConstellationLoader';
import { SkeletonCard } from './loader/SkeletonCard';
import { SkeletonList } from './loader/SkeletonList';
import { SkeletonTableLoader } from './loader/SkeletonTableLoader';
import { SpinnerStates } from './loader/SpinnerStates';
import { StepsLoader } from './loader/StepsLoader';
import { TopProgressBar } from './loader/TopProgressBar';
import { AccountDropdown } from './menu/AccountDropdown';
import { ActionSheet } from './menu/ActionSheet';
import { BreadcrumbOverflowMenu } from './menu/BreadcrumbOverflowMenu';
import { CollapsibleNavMenu } from './menu/CollapsibleNavMenu';
import { ColorLabelMenu } from './menu/ColorLabelMenu';
import { CommandPalette } from './menu/CommandPalette';
import { ContextMenu } from './menu/ContextMenu';
import { DateShortcutsMenu } from './menu/DateShortcutsMenu';
import { EmojiPickerMenu } from './menu/EmojiPickerMenu';
import { ExpandableSearchDock } from './menu/ExpandableSearchDock';
import { ExportMenu } from './menu/ExportMenu';
import { IconSelectMenu } from './menu/IconSelectMenu';
import { KebabCardMenu } from './menu/KebabCardMenu';
import { LanguageSearchMenu } from './menu/LanguageSearchMenu';
import { Menubar } from './menu/Menubar';
import { MoveToFolderMenu } from './menu/MoveToFolderMenu';
import { NotificationTabsMenu } from './menu/NotificationTabsMenu';
import { PinnedListMenu } from './menu/PinnedListMenu';
import { QuickActionsMenu } from './menu/QuickActionsMenu';
import { ReactionPickerMenu } from './menu/ReactionPickerMenu';
import { RowActionsMenu } from './menu/RowActionsMenu';
import { ShareMenu } from './menu/ShareMenu';
import { SortFilterMenu } from './menu/SortFilterMenu';
import { SpeedDialMenu } from './menu/SpeedDialMenu';
import { StatusEmojiMenu } from './menu/StatusEmojiMenu';
import { SubmenuDropdown } from './menu/SubmenuDropdown';
import { TabsOverflowMenu } from './menu/TabsOverflowMenu';
import { WorkspaceSwitchMenu } from './menu/WorkspaceSwitchMenu';
import { AnnouncementNavbar } from './navbar/AnnouncementNavbar';
import { AppHeaderNavbar } from './navbar/AppHeaderNavbar';
import { BottomTabBar } from './navbar/BottomTabBar';
import { BreadcrumbTabsNavbar } from './navbar/BreadcrumbTabsNavbar';
import { CenteredLinksNavbar } from './navbar/CenteredLinksNavbar';
import { CenteredSearchNavbar } from './navbar/CenteredSearchNavbar';
import { CheckoutStepsNavbar } from './navbar/CheckoutStepsNavbar';
import { CommandBarNavbar } from './navbar/CommandBarNavbar';
import { DarkMinimalNavbar } from './navbar/DarkMinimalNavbar';
import { DashboardTopbar } from './navbar/DashboardTopbar';
import { DocsNavbar } from './navbar/DocsNavbar';
import { DoubleDeckNavbar } from './navbar/DoubleDeckNavbar';
import { EditorialNavbar } from './navbar/EditorialNavbar';
import { EventNavbar } from './navbar/EventNavbar';
import { FullscreenMenuNavbar } from './navbar/FullscreenMenuNavbar';
import { GlassPillNavbar } from './navbar/GlassPillNavbar';
import { GradientBorderNavbar } from './navbar/GradientBorderNavbar';
import { HideOnScrollNavbar } from './navbar/HideOnScrollNavbar';
import { IconLabelNavbar } from './navbar/IconLabelNavbar';
import { LanguageNavbar } from './navbar/LanguageNavbar';
import { MegaMenuNavbar } from './navbar/MegaMenuNavbar';
import { NotificationNavbar } from './navbar/NotificationNavbar';
import { PillDropdownNavbar } from './navbar/PillDropdownNavbar';
import { ProfileTabsNavbar } from './navbar/ProfileTabsNavbar';
import { ReadingProgressNavbar } from './navbar/ReadingProgressNavbar';
import { ScrollSpyNavbar } from './navbar/ScrollSpyNavbar';
import { SegmentedNavbar } from './navbar/SegmentedNavbar';
import { ShopNavbar } from './navbar/ShopNavbar';
import { SplitLogoNavbar } from './navbar/SplitLogoNavbar';
import { UnderlineTabsNavbar } from './navbar/UnderlineTabsNavbar';
import { UserMenuNavbar } from './navbar/UserMenuNavbar';
import { AddOnsBuilder } from './pricing/AddOnsBuilder';
import { BookingCheckoutSummary } from './pricing/BookingCheckoutSummary';
import { CouponCheckout } from './pricing/CouponCheckout';
import { CreditPacks } from './pricing/CreditPacks';
import { CurrencyPricing } from './pricing/CurrencyPricing';
import { EditorialPriceList } from './pricing/EditorialPriceList';
import { EnterpriseContactCard } from './pricing/EnterpriseContactCard';
import { FreeVsProLimits } from './pricing/FreeVsProLimits';
import { GlowPlanCards } from './pricing/GlowPlanCards';
import { GradientPricingStack } from './pricing/GradientPricingStack';
import { LifetimeDealCard } from './pricing/LifetimeDealCard';
import { MinimalPricingRows } from './pricing/MinimalPricingRows';
import { PlanDowngradeDialog } from './pricing/PlanDowngradeDialog';
import { PlanRadioSelector } from './pricing/PlanRadioSelector';
import { PricingToggle } from './pricing/PricingToggle';
import { PricingWithFaq } from './pricing/PricingWithFaq';
import { RegionalDiscount } from './pricing/RegionalDiscount';
import { SavingsCalculatorCard } from './pricing/SavingsCalculatorCard';
import { SeatSliderPricing } from './pricing/SeatSliderPricing';
import { SeatStepper } from './pricing/SeatStepper';
import { SinglePlanCard } from './pricing/SinglePlanCard';
import { SquishyPricing } from './pricing/SquishyPricing';
import { StudentPricingCard } from './pricing/StudentPricingCard';
import { TeamPersonalPricing } from './pricing/TeamPersonalPricing';
import { ThreeTierPricing } from './pricing/ThreeTierPricing';
import { TicketTierSelector } from './pricing/TicketTierSelector';
import { TokenPricingTable } from './pricing/TokenPricingTable';
import { TrialTimeline } from './pricing/TrialTimeline';
import { UpgradePrompt } from './pricing/UpgradePrompt';
import { UsageCalculator } from './pricing/UsageCalculator';
import { UsageTierTable } from './pricing/UsageTierTable';
import { AuraGlow } from './shaders/AuraGlow';
import { AuroraCurtain } from './shaders/AuroraCurtain';
import { BackgroundPaths } from './shaders/BackgroundPaths';
import { BokehLights } from './shaders/BokehLights';
import { ClickRipple } from './shaders/ClickRipple';
import { ConicHalo } from './shaders/ConicHalo';
import { CrtScanlines } from './shaders/CrtScanlines';
import { DitherGradient } from './shaders/DitherGradient';
import { DotWave } from './shaders/DotWave';
import { Fireflies } from './shaders/Fireflies';
import { FlickeringGrid } from './shaders/FlickeringGrid';
import { GlowLines } from './shaders/GlowLines';
import { GooeyBlobs } from './shaders/GooeyBlobs';
import { HexagonPattern } from './shaders/HexagonPattern';
import { InfiniteGrid } from './shaders/InfiniteGrid';
import { InteractiveGridPattern } from './shaders/InteractiveGridPattern';
import { LayeredWaves } from './shaders/LayeredWaves';
import { LightRays } from './shaders/LightRays';
import { LiquidChrome } from './shaders/LiquidChrome';
import { MatrixRain } from './shaders/MatrixRain';
import { MeshGradient } from './shaders/MeshGradient';
import { Meteors } from './shaders/Meteors';
import { NetworkParticles } from './shaders/NetworkParticles';
import { NoiseGrain } from './shaders/NoiseGrain';
import { OrbitRings } from './shaders/OrbitRings';
import { PointerWarpGrid } from './shaders/PointerWarpGrid';
import { PrismSweep } from './shaders/PrismSweep';
import { RetroGrid } from './shaders/RetroGrid';
import { RippleBackground } from './shaders/RippleBackground';
import { SiriWave } from './shaders/SiriWave';
import { SpotlightGrid } from './shaders/SpotlightGrid';
import { Starfield } from './shaders/Starfield';
import { TopographyLines } from './shaders/TopographyLines';
import { VortexParticles } from './shaders/VortexParticles';
import { AdminGroupsSidebar } from './sidebar/AdminGroupsSidebar';
import { CalendarSidebar } from './sidebar/CalendarSidebar';
import { ChannelsSidebar } from './sidebar/ChannelsSidebar';
import { ChatListSidebar } from './sidebar/ChatListSidebar';
import { CollapsibleIconSidebar } from './sidebar/CollapsibleIconSidebar';
import { CourseProgressSidebar } from './sidebar/CourseProgressSidebar';
import { DualPaneSidebar } from './sidebar/DualPaneSidebar';
import { FilterSidebar } from './sidebar/FilterSidebar';
import { FloatingIslandSidebar } from './sidebar/FloatingIslandSidebar';
import { FolderTreeSidebar } from './sidebar/FolderTreeSidebar';
import { GlassDockSidebar } from './sidebar/GlassDockSidebar';
import { HoverExpandSidebar } from './sidebar/HoverExpandSidebar';
import { InboxSidebar } from './sidebar/InboxSidebar';
import { KnowledgeBaseSidebar } from './sidebar/KnowledgeBaseSidebar';
import { MiniCartDrawer } from './sidebar/MiniCartDrawer';
import { MobileDrawerSidebar } from './sidebar/MobileDrawerSidebar';
import { MusicLibrarySidebar } from './sidebar/MusicLibrarySidebar';
import { NestedTreeSidebar } from './sidebar/NestedTreeSidebar';
import { NotificationsDrawerSidebar } from './sidebar/NotificationsDrawerSidebar';
import { OutlineSidebar } from './sidebar/OutlineSidebar';
import { ProjectsSidebar } from './sidebar/ProjectsSidebar';
import { PropertiesPanelSidebar } from './sidebar/PropertiesPanelSidebar';
import { SearchableSidebar } from './sidebar/SearchableSidebar';
import { ServerRailSidebar } from './sidebar/ServerRailSidebar';
import { SettingsSidebar } from './sidebar/SettingsSidebar';
import { TocSidebar } from './sidebar/TocSidebar';
import { UpgradeCardSidebar } from './sidebar/UpgradeCardSidebar';
import { WorkspaceSwitcherSidebar } from './sidebar/WorkspaceSwitcherSidebar';
import { AuditLogTable } from './tables/AuditLogTable';
import { ColumnResizeTable } from './tables/ColumnResizeTable';
import { ColumnToggleTable } from './tables/ColumnToggleTable';
import { ComparisonDiffTable } from './tables/ComparisonDiffTable';
import { DensityToggleTable } from './tables/DensityToggleTable';
import { EditableCellTable } from './tables/EditableCellTable';
import { EmptyStateTable } from './tables/EmptyStateTable';
import { ExpandableRowsTable } from './tables/ExpandableRowsTable';
import { FeatureComparisonTable } from './tables/FeatureComparisonTable';
import { FileListTable } from './tables/FileListTable';
import { FilterTabsTable } from './tables/FilterTabsTable';
import { GroupedSubtotalTable } from './tables/GroupedSubtotalTable';
import { HeatmapTable } from './tables/HeatmapTable';
import { InlineAddRowTable } from './tables/InlineAddRowTable';
import { InvoiceTable } from './tables/InvoiceTable';
import { KeyboardGridTable } from './tables/KeyboardGridTable';
import { LeaderboardTable } from './tables/LeaderboardTable';
import { LivePriceTable } from './tables/LivePriceTable';
import { LoadMoreTable } from './tables/LoadMoreTable';
import { OrderTrackingTable } from './tables/OrderTrackingTable';
import { PaginatedTable } from './tables/PaginatedTable';
import { PivotTable } from './tables/PivotTable';
import { ReorderRowsTable } from './tables/ReorderRowsTable';
import { ResponsiveCardTable } from './tables/ResponsiveCardTable';
import { SelectableTable } from './tables/SelectableTable';
import { SortableTable } from './tables/SortableTable';
import { SpecsTable } from './tables/SpecsTable';
import { StickyHeaderTable } from './tables/StickyHeaderTable';
import { TeamStatusTable } from './tables/TeamStatusTable';
import { TimetableTable } from './tables/TimetableTable';
import { TransactionsTable } from './tables/TransactionsTable';
import { TreeTable } from './tables/TreeTable';
import { AudioQuoteTestimonial } from './testimonials/AudioQuoteTestimonial';
import { AvatarCloudTestimonial } from './testimonials/AvatarCloudTestimonial';
import { AvatarPickerTestimonial } from './testimonials/AvatarPickerTestimonial';
import { BeforeAfterTestimonial } from './testimonials/BeforeAfterTestimonial';
import { CaseStudyCard } from './testimonials/CaseStudyCard';
import { CaseStudyTimeline } from './testimonials/CaseStudyTimeline';
import { ChatScreenshotTestimonial } from './testimonials/ChatScreenshotTestimonial';
import { CompactTestimonialList } from './testimonials/CompactTestimonialList';
import { GradientBorderQuote } from './testimonials/GradientBorderQuote';
import { HandwrittenNoteTestimonial } from './testimonials/HandwrittenNoteTestimonial';
import { HighlightedQuoteTestimonial } from './testimonials/HighlightedQuoteTestimonial';
import { LogoMetricTestimonial } from './testimonials/LogoMetricTestimonial';
import { MarqueeTestimonials } from './testimonials/MarqueeTestimonials';
import { PressQuotes } from './testimonials/PressQuotes';
import { QuoteRotator } from './testimonials/QuoteRotator';
import { QuoteSpotlight } from './testimonials/QuoteSpotlight';
import { RatingStrip } from './testimonials/RatingStrip';
import { RatingSummary } from './testimonials/RatingSummary';
import { ReviewFilterList } from './testimonials/ReviewFilterList';
import { ReviewWithReply } from './testimonials/ReviewWithReply';
import { RoleTabsTestimonials } from './testimonials/RoleTabsTestimonials';
import { ScoreCardsTestimonial } from './testimonials/ScoreCardsTestimonial';
import { SocialPostCards } from './testimonials/SocialPostCards';
import { StackedTestimonials } from './testimonials/StackedTestimonials';
import { TestimonialCarousel } from './testimonials/TestimonialCarousel';
import { TestimonialWall } from './testimonials/TestimonialWall';
import { TiltTestimonialCard } from './testimonials/TiltTestimonialCard';
import { VideoGridTestimonials } from './testimonials/VideoGridTestimonials';
import { VideoTestimonial } from './testimonials/VideoTestimonial';
import { AnimatedUnderlines } from './text/AnimatedUnderlines';
import { AuroraText } from './text/AuroraText';
import { BounceHoverText } from './text/BounceHoverText';
import { ComicText } from './text/ComicText';
import { CountdownDigits } from './text/CountdownDigits';
import { CubeRotateWords } from './text/CubeRotateWords';
import { CurvedText } from './text/CurvedText';
import { DecryptText } from './text/DecryptText';
import { FlipText3D } from './text/FlipText3D';
import { FocusBlurText } from './text/FocusBlurText';
import { GlitchText } from './text/GlitchText';
import { GradientStrokeText } from './text/GradientStrokeText';
import { GradientText } from './text/GradientText';
import { HandwritingSignature } from './text/HandwritingSignature';
import { HighlightSweepText } from './text/HighlightSweepText';
import { HighlighterText } from './text/HighlighterText';
import { KbdShortcuts } from './text/KbdShortcuts';
import { KineticLetterWave } from './text/KineticLetterWave';
import { KineticMarquee } from './text/KineticMarquee';
import { LineShadowText } from './text/LineShadowText';
import { MaskedLineReveal } from './text/MaskedLineReveal';
import { MorphingText } from './text/MorphingText';
import { NumberTicker } from './text/NumberTicker';
import { OutlineFillText } from './text/OutlineFillText';
import { RainbowUnderlineText } from './text/RainbowUnderlineText';
import { ShadowStackText } from './text/ShadowStackText';
import { SparklesText } from './text/SparklesText';
import { SpinningText } from './text/SpinningText';
import { SplitFlapText } from './text/SplitFlapText';
import { StrikeReplaceText } from './text/StrikeReplaceText';
import { TextMaskReveal } from './text/TextMaskReveal';
import { TextRotate } from './text/TextRotate';
import { TypingAnimation } from './text/TypingAnimation';
import { VariableWeightText } from './text/VariableWeightText';
import { WavyText } from './text/WavyText';
import { WordReveal } from './text/WordReveal';
import { AirplaneModeToggle } from './toggle/AirplaneModeToggle';
import { AnimatedThemeToggler } from './toggle/AnimatedThemeToggler';
import { AsyncSwitch } from './toggle/AsyncSwitch';
import { BellMuteToggle } from './toggle/BellMuteToggle';
import { CurrencyToggle } from './toggle/CurrencyToggle';
import { FollowToggleButton } from './toggle/FollowToggleButton';
import { HamburgerSwap } from './toggle/HamburgerSwap';
import { IconKnobSwitch } from './toggle/IconKnobSwitch';
import { LiquidFillSwitch } from './toggle/LiquidFillSwitch';
import { LockUnlockToggle } from './toggle/LockUnlockToggle';
import { MediaDeviceToggles } from './toggle/MediaDeviceToggles';
import { MorphCheckSwitch } from './toggle/MorphCheckSwitch';
import { NeumorphicSwitch } from './toggle/NeumorphicSwitch';
import { OnOffLabelSwitch } from './toggle/OnOffLabelSwitch';
import { PasswordVisibilityToggle } from './toggle/PasswordVisibilityToggle';
import { PlayPauseSwap } from './toggle/PlayPauseSwap';
import { SettingsSwitchList } from './toggle/SettingsSwitchList';
import { StretchySwitch } from './toggle/StretchySwitch';
import { SwitchCard } from './toggle/SwitchCard';
import { SwitchSizes } from './toggle/SwitchSizes';
import { TextToggleGroup } from './toggle/TextToggleGroup';
import { ThemeControllerRadios } from './toggle/ThemeControllerRadios';
import { ThemeSwitch } from './toggle/ThemeSwitch';
import { TriStateToggle } from './toggle/TriStateToggle';
import { ViewModeToggle } from './toggle/ViewModeToggle';
import { AvatarStackTooltip } from './tooltips/AvatarStackTooltip';
import { BouncyTooltip } from './tooltips/BouncyTooltip';
import { ColorTooltipVariants } from './tooltips/ColorTooltipVariants';
import { CopyTooltip } from './tooltips/CopyTooltip';
import { DelayedTooltip } from './tooltips/DelayedTooltip';
import { DimensionsPopover } from './tooltips/DimensionsPopover';
import { DisabledReasonTooltip } from './tooltips/DisabledReasonTooltip';
import { FollowCursorTooltip } from './tooltips/FollowCursorTooltip';
import { GlossaryTooltip } from './tooltips/GlossaryTooltip';
import { HoverCardTooltip } from './tooltips/HoverCardTooltip';
import { ImageHotspots } from './tooltips/ImageHotspots';
import { InfoIconTooltip } from './tooltips/InfoIconTooltip';
import { LinkPreviewTooltip } from './tooltips/LinkPreviewTooltip';
import { OnboardingTour } from './tooltips/OnboardingTour';
import { OverflowTagsPopover } from './tooltips/OverflowTagsPopover';
import { PlacementTooltips } from './tooltips/PlacementTooltips';
import { PopconfirmDelete } from './tooltips/PopconfirmDelete';
import { ReactionTooltip } from './tooltips/ReactionTooltip';
import { SharedCursorTooltip } from './tooltips/SharedCursorTooltip';
import { ShortcutsHelpPopover } from './tooltips/ShortcutsHelpPopover';
import { SliderValueTooltip } from './tooltips/SliderValueTooltip';
import { StatusDotTooltip } from './tooltips/StatusDotTooltip';
import { StepperTooltips } from './tooltips/StepperTooltips';
import { ToastStack } from './tooltips/ToastStack';
import { Toggletip } from './tooltips/Toggletip';
import { ToolbarTooltips } from './tooltips/ToolbarTooltips';
import { TruncatedTextTooltip } from './tooltips/TruncatedTextTooltip';
import { ValidationPopover } from './tooltips/ValidationPopover';

/** Registry components render from their own file and support light and dark mode. */
export const registryComponents: Record<string, ComponentType> = {
  "agent-plan-checklist": AgentPlanChecklist,
  "agent-trace": AgentTrace,
  "ai-summary-card": AiSummaryCard,
  "answer-feedback-form": AnswerFeedbackForm,
  "artifact-panel": ArtifactPanel,
  "attachment-composer": AttachmentComposer,
  "chat-bubble-status": ChatBubbleStatus,
  "chat-history-list": ChatHistoryList,
  "chat-mode-composer": ChatModeComposer,
  "chat-thread": ChatThread,
  "clarifying-questionnaire": ClarifyingQuestionnaire,
  "code-answer": CodeAnswer,
  "context-files-panel": ContextFilesPanel,
  "context-meter": ContextMeter,
  "diff-suggestion-card": DiffSuggestionCard,
  "image-generation": ImageGeneration,
  "memory-chips-panel": MemoryChipsPanel,
  "message-actions": MessageActions,
  "model-selector": ModelSelector,
  "prompt-input-bar": PromptInputBar,
  "prompt-library-picker": PromptLibraryPicker,
  "response-variants": ResponseVariants,
  "slash-command-menu": SlashCommandMenu,
  "sources-answer": SourcesAnswer,
  "streaming-message": StreamingMessage,
  "suggested-prompts": SuggestedPrompts,
  "support-widget": SupportWidget,
  "thinking-accordion": ThinkingAccordion,
  "tone-rewrite-box": ToneRewriteBox,
  "tool-call-card": ToolCallCard,
  "typing-indicator": TypingIndicator,
  "voice-orb": VoiceOrb,
  "voice-recorder-input": VoiceRecorderInput,
  "bug-triage-board": BugTriageBoard,
  "candidate-pipeline-board": CandidatePipelineBoard,
  "content-calendar": ContentCalendar,
  "content-pipeline-board": ContentPipelineBoard,
  "customer-journey-board": CustomerJourneyBoard,
  "drag-drop-kanban": DragDropKanban,
  "eisenhower-matrix": EisenhowerMatrix,
  "feature-voting-board": FeatureVotingBoard,
  "gantt-timeline": GanttTimeline,
  "grouped-issue-list": GroupedIssueList,
  "habit-tracker-board": HabitTrackerBoard,
  "hiring-pipeline": HiringPipeline,
  "inline-add-board": InlineAddBoard,
  "issue-card-detail": IssueCardDetail,
  "milestone-tracker": MilestoneTracker,
  "mood-board": MoodBoard,
  "now-next-later-roadmap": NowNextLaterRoadmap,
  "okr-board": OkrBoard,
  "planning-poker-board": PlanningPokerBoard,
  "release-train-board": ReleaseTrainBoard,
  "retro-board": RetroBoard,
  "sales-pipeline": SalesPipeline,
  "sprint-burndown-board": SprintBurndownBoard,
  "sticky-notes-wall": StickyNotesWall,
  "swimlane-board": SwimlaneBoard,
  "time-block-planner": TimeBlockPlanner,
  "user-story-map": UserStoryMap,
  "wip-limit-board": WipLimitBoard,
  "avatar-button": AvatarButton,
  "badge-count-button": BadgeCountButton,
  "barrel-roll-navigation": BarrelRollNavigation,
  "border-beam-button": BorderBeamButton,
  "button-group": ButtonGroup,
  "button-variants": ButtonVariants,
  "circle-reveal-button": CircleRevealButton,
  "confetti-button": ConfettiButton,
  "cool-mode-button": CoolModeButton,
  "copy-link-button": CopyLinkButton,
  "download-progress-button": DownloadProgressButton,
  "elastic-press-button": ElasticPressButton,
  "elastic-send-button": ElasticSendButton,
  "expand-icon-button": ExpandIconButton,
  "flip-button3-d": FlipButton3D,
  "floating-action-button": FloatingActionButton,
  "glitch-button": GlitchButton,
  "gradient-outline-button": GradientOutlineButton,
  "hold-to-confirm-button": HoldToConfirmButton,
  "interactive-hover-button": InteractiveHoverButton,
  "kbd-shortcut-button": KbdShortcutButton,
  "like-burst-button": LikeBurstButton,
  "magnetic-pull-button": MagneticPullButton,
  "neon-button": NeonButton,
  "pulsating-button": PulsatingButton,
  "push-button": PushButton,
  "rainbow-button": RainbowButton,
  "resend-code-button": ResendCodeButton,
  "ripple-button": RippleButton,
  "shimmer-button": ShimmerButton,
  "shiny-button": ShinyButton,
  "skeuomorphic-button": SkeuomorphicButton,
  "slide-arrow-button": SlideArrowButton,
  "social-login-buttons": SocialLoginButtons,
  "split-button": SplitButton,
  "swipe-to-confirm": SwipeToConfirm,
  "animated-beam-card": AnimatedBeamCard,
  "animated-notification-list": AnimatedNotificationList,
  "bento-features": BentoFeatures,
  "blog-post-card": BlogPostCard,
  "book-cover-card": BookCoverCard,
  "carousel-card": CarouselCard,
  "code-comparison": CodeComparison,
  "collectible-card": CollectibleCard,
  "course-card": CourseCard,
  "event-ticket-card": EventTicketCard,
  "expandable-stat-card": ExpandableStatCard,
  "focus-timer-card": FocusTimerCard,
  "glare-hover-card": GlareHoverCard,
  "holographic-event-pass": HolographicEventPass,
  "hover-gallery-card": HoverGalleryCard,
  "interactive-product-inspector": InteractiveProductInspector,
  "invoice-preview-card": InvoicePreviewCard,
  "job-opportunity-card": JobOpportunityCard,
  "layered-project-card": LayeredProjectCard,
  "lens-card": LensCard,
  "mask-shapes-card": MaskShapesCard,
  "music-player-card": MusicPlayerCard,
  "neon-gradient-card": NeonGradientCard,
  "orbiting-circles": OrbitingCircles,
  "podcast-episode-card": PodcastEpisodeCard,
  "profile-cover-card": ProfileCoverCard,
  "property-listing-card": PropertyListingCard,
  "recipe-card": RecipeCard,
  "repo-card": RepoCard,
  "safari-mockup": SafariMockup,
  "seller-trust-card": SellerTrustCard,
  "shine-border-card": ShineBorderCard,
  "specialist-picker": SpecialistPicker,
  "spotlight-card": SpotlightCard,
  "stat-card": StatCard,
  "team-member-card": TeamMemberCard,
  "tweet-card": TweetCard,
  "area-range-chart": AreaRangeChart,
  "box-plot-chart": BoxPlotChart,
  "bubble-chart": BubbleChart,
  "bullet-chart": BulletChart,
  "candlestick-chart": CandlestickChart,
  "diverging-bar-chart": DivergingBarChart,
  "dot-plot-chart": DotPlotChart,
  "forecast-line-chart": ForecastLineChart,
  "gauge-chart": GaugeChart,
  "grouped-bar-chart": GroupedBarChart,
  "interactive-bar-chart": InteractiveBarChart,
  "interactive-donut-chart": InteractiveDonutChart,
  "lollipop-chart": LollipopChart,
  "pareto-chart": ParetoChart,
  "percent-stacked-bar": PercentStackedBar,
  "polar-area-chart": PolarAreaChart,
  "punch-card-chart": PunchCardChart,
  "radar-chart": RadarChart,
  "radial-bar-chart": RadialBarChart,
  "radial-progress-stats": RadialProgressStats,
  "range-band-chart": RangeBandChart,
  "scatter-plot": ScatterPlot,
  "slope-chart": SlopeChart,
  "stacked-area-chart": StackedAreaChart,
  "step-line-chart": StepLineChart,
  "streamgraph-chart": StreamgraphChart,
  "sunburst-chart": SunburstChart,
  "treemap-chart": TreemapChart,
  "waterfall-chart": WaterfallChart,
  "add-on-checkboxes": AddOnCheckboxes,
  "allergen-checkboxes": AllergenCheckboxes,
  "animated-checklist": AnimatedChecklist,
  "checkbox-cards": CheckboxCards,
  "checkbox-group-described": CheckboxGroupDescribed,
  "chip-checkboxes": ChipCheckboxes,
  "circle-checkbox": CircleCheckbox,
  "color-swatch-checkboxes": ColorSwatchCheckboxes,
  "facet-count-checkboxes": FacetCountCheckboxes,
  "goal-card-checkboxes": GoalCardCheckboxes,
  "grocery-checklist": GroceryChecklist,
  "heart-checkbox": HeartCheckbox,
  "image-picker-checkbox": ImagePickerCheckbox,
  "indeterminate-tree": IndeterminateTree,
  "interest-chips": InterestChips,
  "jelly-checkbox": JellyCheckbox,
  "neon-checkbox": NeonCheckbox,
  "permissions-matrix": PermissionsMatrix,
  "range-select-list": RangeSelectList,
  "retro-checkbox": RetroCheckbox,
  "select-all-cards": SelectAllCards,
  "size-checkbox-grid": SizeCheckboxGrid,
  "svg-draw-checkbox": SvgDrawCheckbox,
  "swap-icon-checkbox": SwapIconCheckbox,
  "terms-consent-form": TermsConsentForm,
  "validated-checkbox": ValidatedCheckbox,
  "weekday-picker": WeekdayPicker,
  "before-after-slider-cta": BeforeAfterSliderCta,
  "book-demo-cta": BookDemoCta,
  "community-join-cta": CommunityJoinCta,
  "contact-sales-cta": ContactSalesCta,
  "decision-path-cta": DecisionPathCta,
  "download-apps-cta": DownloadAppsCta,
  "early-access-code-cta": EarlyAccessCodeCta,
  "exit-intent-cta": ExitIntentCta,
  "gradient-shapes-cta": GradientShapesCta,
  "inline-banner-cta": InlineBannerCta,
  "inline-newsletter-cta": InlineNewsletterCta,
  "order-success-card": OrderSuccessCard,
  "pricing-teaser-cta": PricingTeaserCta,
  "quiz-cta": QuizCta,
  "rating-feedback-cta": RatingFeedbackCta,
  "referral-cta": ReferralCta,
  "split-image-cta": SplitImageCta,
  "spotlight-cta": SpotlightCta,
  "stats-cta": StatsCta,
  "sticky-mobile-cta": StickyMobileCta,
  "testimonial-cta": TestimonialCta,
  "trial-checklist-cta": TrialChecklistCta,
  "trial-expiry-cta": TrialExpiryCta,
  "video-demo-cta": VideoDemoCta,
  "webinar-cta": WebinarCta,
  "activity-feed": ActivityFeed,
  "application-tracker": ApplicationTracker,
  "appointment-manager": AppointmentManager,
  "appointments-today": AppointmentsToday,
  "billing-summary": BillingSummary,
  "campaign-stats-widget": CampaignStatsWidget,
  "cashflow-widget": CashflowWidget,
  "contribution-heatmap": ContributionHeatmap,
  "conversion-breakdown": ConversionBreakdown,
  "crypto-portfolio": CryptoPortfolio,
  "dark-metric-panel": DarkMetricPanel,
  "deployments-widget": DeploymentsWidget,
  "expense-categories-widget": ExpenseCategoriesWidget,
  "goal-gauge": GoalGauge,
  "horizontal-timeline": HorizontalTimeline,
  "inventory-alerts-widget": InventoryAlertsWidget,
  "kpi-grid": KpiGrid,
  "matchday-scoreboard": MatchdayScoreboard,
  "project-progress-list": ProjectProgressList,
  "quick-notes-widget": QuickNotesWidget,
  "realtime-visitors": RealtimeVisitors,
  "recent-sales": RecentSales,
  "resizable-panels": ResizablePanels,
  "revenue-overview": RevenueOverview,
  "server-health-panel": ServerHealthPanel,
  "service-uptime": ServiceUptime,
  "setup-steps-widget": SetupStepsWidget,
  "stat-group": StatGroup,
  "storage-usage": StorageUsage,
  "support-sla-widget": SupportSlaWidget,
  "tasks-widget": TasksWidget,
  "team-presence-widget": TeamPresenceWidget,
  "team-workload": TeamWorkload,
  "top-countries": TopCountries,
  "upcoming-events": UpcomingEvents,
  "weather-widget": WeatherWidget,
  "welcome-banner": WelcomeBanner,
  "accordion-sitemap-footer": AccordionSitemapFooter,
  "app-download-footer": AppDownloadFooter,
  "back-to-top-footer": BackToTopFooter,
  "changelog-footer": ChangelogFooter,
  "columns-newsletter-footer": ColumnsNewsletterFooter,
  "community-footer": CommunityFooter,
  "contact-form-footer": ContactFormFooter,
  "contact-info-footer": ContactInfoFooter,
  "cta-band-footer": CtaBandFooter,
  "docs-pager-footer": DocsPagerFooter,
  "ecommerce-trust-footer": EcommerceTrustFooter,
  "floating-card-footer": FloatingCardFooter,
  "gradient-brand-footer": GradientBrandFooter,
  "legal-bar-footer": LegalBarFooter,
  "magazine-footer": MagazineFooter,
  "marquee-footer": MarqueeFooter,
  "mega-links-footer": MegaLinksFooter,
  "minimal-centered-footer": MinimalCenteredFooter,
  "offices-footer": OfficesFooter,
  "partners-footer": PartnersFooter,
  "portfolio-footer": PortfolioFooter,
  "preferences-footer": PreferencesFooter,
  "social-wall-footer": SocialWallFooter,
  "startup-badges-footer": StartupBadgesFooter,
  "status-footer": StatusFooter,
  "wave-footer": WaveFooter,
  "wordmark-footer": WordmarkFooter,
  "address-fieldset": AddressFieldset,
  "auction-bid-panel": AuctionBidPanel,
  "autocomplete-input": AutocompleteInput,
  "availability-slot-picker": AvailabilitySlotPicker,
  "avatar-uploader": AvatarUploader,
  "change-password-form": ChangePasswordForm,
  "color-picker-input": ColorPickerInput,
  "credit-card-form": CreditCardForm,
  "currency-converter-form": CurrencyConverterForm,
  "date-range-calendar": DateRangeCalendar,
  "dual-range-slider": DualRangeSlider,
  "event-rsvp-form": EventRsvpForm,
  "feedback-form": FeedbackForm,
  "file-dropzone": FileDropzone,
  "floating-label-input": FloatingLabelInput,
  "forgot-password": ForgotPassword,
  "inline-date-picker": InlineDatePicker,
  "inline-edit-field": InlineEditField,
  "input-group-showcase": InputGroupShowcase,
  "marked-range-slider": MarkedRangeSlider,
  "multi-select-combobox": MultiSelectCombobox,
  "newsletter-topics-form": NewsletterTopicsForm,
  "nps-survey": NpsSurvey,
  "number-stepper-input": NumberStepperInput,
  "otp-input": OtpInput,
  "password-strength": PasswordStrength,
  "phone-input": PhoneInput,
  "product-variant-picker": ProductVariantPicker,
  "quick-apply-form": QuickApplyForm,
  "rating-matrix-form": RatingMatrixForm,
  "reservation-form": ReservationForm,
  "shipping-method-selector": ShippingMethodSelector,
  "sign-in-form": SignInForm,
  "signature-pad": SignaturePad,
  "star-rating-input": StarRatingInput,
  "tag-input": TagInput,
  "time-field-input": TimeFieldInput,
  "transfer-list": TransferList,
  "typed-signature-field": TypedSignatureField,
  "validated-contact-form": ValidatedContactForm,
  "voice-note-composer": VoiceNoteComposer,
  "wizard-form": WizardForm,
  "agency-showcase-hero": AgencyShowcaseHero,
  "aurora-blob-hero": AuroraBlobHero,
  "beam-spotlight-hero": BeamSpotlightHero,
  "big-gradient-hero": BigGradientHero,
  "checklist-hero": ChecklistHero,
  "code-editor-hero": CodeEditorHero,
  "countdown-hero": CountdownHero,
  "editorial-hero": EditorialHero,
  "floating-cards-hero": FloatingCardsHero,
  "globe-hero": GlobeHero,
  "gradient-mesh-hero": GradientMeshHero,
  "grid-glow-hero": GridGlowHero,
  "hover3-d-hero": Hover3DHero,
  "icon-cloud-hero": IconCloudHero,
  "launch-badge-hero": LaunchBadgeHero,
  "logo-cloud-hero": LogoCloudHero,
  "map-pins-hero": MapPinsHero,
  "metrics-hero": MetricsHero,
  "overlay-image-hero": OverlayImageHero,
  "persona-tabs-hero": PersonaTabsHero,
  "phone-mockup-hero": PhoneMockupHero,
  "scanline-launch-hero": ScanlineLaunchHero,
  "search-hero": SearchHero,
  "social-proof-hero": SocialProofHero,
  "split-mockup-hero": SplitMockupHero,
  "stats-ticker-hero": StatsTickerHero,
  "terminal-hero": TerminalHero,
  "tilted-screens-hero": TiltedScreensHero,
  "typewriter-hero": TypewriterHero,
  "video-preview-hero": VideoPreviewHero,
  "waitlist-hero": WaitlistHero,
  "battery-charge-loader": BatteryChargeLoader,
  "bouncing-ball-loader": BouncingBallLoader,
  "bouncing-dots": BouncingDots,
  "chat-skeleton-loader": ChatSkeletonLoader,
  "circular-progress": CircularProgress,
  "clock-loader": ClockLoader,
  "cube-grid": CubeGrid,
  "dna-helix-loader": DnaHelixLoader,
  "equalizer-bars": EqualizerBars,
  "flipping-square": FlippingSquare,
  "gradient-ring-spinner": GradientRingSpinner,
  "hourglass-loader": HourglassLoader,
  "indeterminate-bar": IndeterminateBar,
  "infinity-loader": InfinityLoader,
  "letter-wave": LetterWave,
  "loading-button": LoadingButton,
  "loading-variants": LoadingVariants,
  "morph-shape-loader": MorphShapeLoader,
  "orbit-dots-loader": OrbitDotsLoader,
  "pendulum-loader": PendulumLoader,
  "percent-counter-loader": PercentCounterLoader,
  "pulse-rings": PulseRings,
  "radar-scan-loader": RadarScanLoader,
  "segment-spinner": SegmentSpinner,
  "shimmer-image-grid": ShimmerImageGrid,
  "signal-constellation-loader": SignalConstellationLoader,
  "skeleton-card": SkeletonCard,
  "skeleton-list": SkeletonList,
  "skeleton-table-loader": SkeletonTableLoader,
  "spinner-states": SpinnerStates,
  "steps-loader": StepsLoader,
  "top-progress-bar": TopProgressBar,
  "account-dropdown": AccountDropdown,
  "action-sheet": ActionSheet,
  "breadcrumb-overflow-menu": BreadcrumbOverflowMenu,
  "collapsible-nav-menu": CollapsibleNavMenu,
  "color-label-menu": ColorLabelMenu,
  "command-palette": CommandPalette,
  "context-menu": ContextMenu,
  "date-shortcuts-menu": DateShortcutsMenu,
  "emoji-picker-menu": EmojiPickerMenu,
  "expandable-search-dock": ExpandableSearchDock,
  "export-menu": ExportMenu,
  "icon-select-menu": IconSelectMenu,
  "kebab-card-menu": KebabCardMenu,
  "language-search-menu": LanguageSearchMenu,
  "menubar": Menubar,
  "move-to-folder-menu": MoveToFolderMenu,
  "notification-tabs-menu": NotificationTabsMenu,
  "pinned-list-menu": PinnedListMenu,
  "quick-actions-menu": QuickActionsMenu,
  "reaction-picker-menu": ReactionPickerMenu,
  "row-actions-menu": RowActionsMenu,
  "share-menu": ShareMenu,
  "sort-filter-menu": SortFilterMenu,
  "speed-dial-menu": SpeedDialMenu,
  "status-emoji-menu": StatusEmojiMenu,
  "submenu-dropdown": SubmenuDropdown,
  "tabs-overflow-menu": TabsOverflowMenu,
  "workspace-switch-menu": WorkspaceSwitchMenu,
  "announcement-navbar": AnnouncementNavbar,
  "app-header-navbar": AppHeaderNavbar,
  "bottom-tab-bar": BottomTabBar,
  "breadcrumb-tabs-navbar": BreadcrumbTabsNavbar,
  "centered-links-navbar": CenteredLinksNavbar,
  "centered-search-navbar": CenteredSearchNavbar,
  "checkout-steps-navbar": CheckoutStepsNavbar,
  "command-bar-navbar": CommandBarNavbar,
  "dark-minimal-navbar": DarkMinimalNavbar,
  "dashboard-topbar": DashboardTopbar,
  "docs-navbar": DocsNavbar,
  "double-deck-navbar": DoubleDeckNavbar,
  "editorial-navbar": EditorialNavbar,
  "event-navbar": EventNavbar,
  "fullscreen-menu-navbar": FullscreenMenuNavbar,
  "glass-pill-navbar": GlassPillNavbar,
  "gradient-border-navbar": GradientBorderNavbar,
  "hide-on-scroll-navbar": HideOnScrollNavbar,
  "icon-label-navbar": IconLabelNavbar,
  "language-navbar": LanguageNavbar,
  "mega-menu-navbar": MegaMenuNavbar,
  "notification-navbar": NotificationNavbar,
  "pill-dropdown-navbar": PillDropdownNavbar,
  "profile-tabs-navbar": ProfileTabsNavbar,
  "reading-progress-navbar": ReadingProgressNavbar,
  "scroll-spy-navbar": ScrollSpyNavbar,
  "segmented-navbar": SegmentedNavbar,
  "shop-navbar": ShopNavbar,
  "split-logo-navbar": SplitLogoNavbar,
  "underline-tabs-navbar": UnderlineTabsNavbar,
  "user-menu-navbar": UserMenuNavbar,
  "add-ons-builder": AddOnsBuilder,
  "booking-checkout-summary": BookingCheckoutSummary,
  "coupon-checkout": CouponCheckout,
  "credit-packs": CreditPacks,
  "currency-pricing": CurrencyPricing,
  "editorial-price-list": EditorialPriceList,
  "enterprise-contact-card": EnterpriseContactCard,
  "free-vs-pro-limits": FreeVsProLimits,
  "glow-plan-cards": GlowPlanCards,
  "gradient-pricing-stack": GradientPricingStack,
  "lifetime-deal-card": LifetimeDealCard,
  "minimal-pricing-rows": MinimalPricingRows,
  "plan-downgrade-dialog": PlanDowngradeDialog,
  "plan-radio-selector": PlanRadioSelector,
  "pricing-toggle": PricingToggle,
  "pricing-with-faq": PricingWithFaq,
  "regional-discount": RegionalDiscount,
  "savings-calculator-card": SavingsCalculatorCard,
  "seat-slider-pricing": SeatSliderPricing,
  "seat-stepper": SeatStepper,
  "single-plan-card": SinglePlanCard,
  "squishy-pricing": SquishyPricing,
  "student-pricing-card": StudentPricingCard,
  "team-personal-pricing": TeamPersonalPricing,
  "three-tier-pricing": ThreeTierPricing,
  "ticket-tier-selector": TicketTierSelector,
  "token-pricing-table": TokenPricingTable,
  "trial-timeline": TrialTimeline,
  "upgrade-prompt": UpgradePrompt,
  "usage-calculator": UsageCalculator,
  "usage-tier-table": UsageTierTable,
  "aura-glow": AuraGlow,
  "aurora-curtain": AuroraCurtain,
  "background-paths": BackgroundPaths,
  "bokeh-lights": BokehLights,
  "click-ripple": ClickRipple,
  "conic-halo": ConicHalo,
  "crt-scanlines": CrtScanlines,
  "dither-gradient": DitherGradient,
  "dot-wave": DotWave,
  "fireflies": Fireflies,
  "flickering-grid": FlickeringGrid,
  "glow-lines": GlowLines,
  "gooey-blobs": GooeyBlobs,
  "hexagon-pattern": HexagonPattern,
  "infinite-grid": InfiniteGrid,
  "interactive-grid-pattern": InteractiveGridPattern,
  "layered-waves": LayeredWaves,
  "light-rays": LightRays,
  "liquid-chrome": LiquidChrome,
  "matrix-rain": MatrixRain,
  "mesh-gradient": MeshGradient,
  "meteors": Meteors,
  "network-particles": NetworkParticles,
  "noise-grain": NoiseGrain,
  "orbit-rings": OrbitRings,
  "pointer-warp-grid": PointerWarpGrid,
  "prism-sweep": PrismSweep,
  "retro-grid": RetroGrid,
  "ripple-background": RippleBackground,
  "siri-wave": SiriWave,
  "spotlight-grid": SpotlightGrid,
  "starfield": Starfield,
  "topography-lines": TopographyLines,
  "vortex-particles": VortexParticles,
  "admin-groups-sidebar": AdminGroupsSidebar,
  "calendar-sidebar": CalendarSidebar,
  "channels-sidebar": ChannelsSidebar,
  "chat-list-sidebar": ChatListSidebar,
  "collapsible-icon-sidebar": CollapsibleIconSidebar,
  "course-progress-sidebar": CourseProgressSidebar,
  "dual-pane-sidebar": DualPaneSidebar,
  "filter-sidebar": FilterSidebar,
  "floating-island-sidebar": FloatingIslandSidebar,
  "folder-tree-sidebar": FolderTreeSidebar,
  "glass-dock-sidebar": GlassDockSidebar,
  "hover-expand-sidebar": HoverExpandSidebar,
  "inbox-sidebar": InboxSidebar,
  "knowledge-base-sidebar": KnowledgeBaseSidebar,
  "mini-cart-drawer": MiniCartDrawer,
  "mobile-drawer-sidebar": MobileDrawerSidebar,
  "music-library-sidebar": MusicLibrarySidebar,
  "nested-tree-sidebar": NestedTreeSidebar,
  "notifications-drawer-sidebar": NotificationsDrawerSidebar,
  "outline-sidebar": OutlineSidebar,
  "projects-sidebar": ProjectsSidebar,
  "properties-panel-sidebar": PropertiesPanelSidebar,
  "searchable-sidebar": SearchableSidebar,
  "server-rail-sidebar": ServerRailSidebar,
  "settings-sidebar": SettingsSidebar,
  "toc-sidebar": TocSidebar,
  "upgrade-card-sidebar": UpgradeCardSidebar,
  "workspace-switcher-sidebar": WorkspaceSwitcherSidebar,
  "audit-log-table": AuditLogTable,
  "column-resize-table": ColumnResizeTable,
  "column-toggle-table": ColumnToggleTable,
  "comparison-diff-table": ComparisonDiffTable,
  "density-toggle-table": DensityToggleTable,
  "editable-cell-table": EditableCellTable,
  "empty-state-table": EmptyStateTable,
  "expandable-rows-table": ExpandableRowsTable,
  "feature-comparison-table": FeatureComparisonTable,
  "file-list-table": FileListTable,
  "filter-tabs-table": FilterTabsTable,
  "grouped-subtotal-table": GroupedSubtotalTable,
  "heatmap-table": HeatmapTable,
  "inline-add-row-table": InlineAddRowTable,
  "invoice-table": InvoiceTable,
  "keyboard-grid-table": KeyboardGridTable,
  "leaderboard-table": LeaderboardTable,
  "live-price-table": LivePriceTable,
  "load-more-table": LoadMoreTable,
  "order-tracking-table": OrderTrackingTable,
  "paginated-table": PaginatedTable,
  "pivot-table": PivotTable,
  "reorder-rows-table": ReorderRowsTable,
  "responsive-card-table": ResponsiveCardTable,
  "selectable-table": SelectableTable,
  "sortable-table": SortableTable,
  "specs-table": SpecsTable,
  "sticky-header-table": StickyHeaderTable,
  "team-status-table": TeamStatusTable,
  "timetable-table": TimetableTable,
  "transactions-table": TransactionsTable,
  "tree-table": TreeTable,
  "audio-quote-testimonial": AudioQuoteTestimonial,
  "avatar-cloud-testimonial": AvatarCloudTestimonial,
  "avatar-picker-testimonial": AvatarPickerTestimonial,
  "before-after-testimonial": BeforeAfterTestimonial,
  "case-study-card": CaseStudyCard,
  "case-study-timeline": CaseStudyTimeline,
  "chat-screenshot-testimonial": ChatScreenshotTestimonial,
  "compact-testimonial-list": CompactTestimonialList,
  "gradient-border-quote": GradientBorderQuote,
  "handwritten-note-testimonial": HandwrittenNoteTestimonial,
  "highlighted-quote-testimonial": HighlightedQuoteTestimonial,
  "logo-metric-testimonial": LogoMetricTestimonial,
  "marquee-testimonials": MarqueeTestimonials,
  "press-quotes": PressQuotes,
  "quote-rotator": QuoteRotator,
  "quote-spotlight": QuoteSpotlight,
  "rating-strip": RatingStrip,
  "rating-summary": RatingSummary,
  "review-filter-list": ReviewFilterList,
  "review-with-reply": ReviewWithReply,
  "role-tabs-testimonials": RoleTabsTestimonials,
  "score-cards-testimonial": ScoreCardsTestimonial,
  "social-post-cards": SocialPostCards,
  "stacked-testimonials": StackedTestimonials,
  "testimonial-carousel": TestimonialCarousel,
  "testimonial-wall": TestimonialWall,
  "tilt-testimonial-card": TiltTestimonialCard,
  "video-grid-testimonials": VideoGridTestimonials,
  "video-testimonial": VideoTestimonial,
  "animated-underlines": AnimatedUnderlines,
  "aurora-text": AuroraText,
  "bounce-hover-text": BounceHoverText,
  "comic-text": ComicText,
  "countdown-digits": CountdownDigits,
  "cube-rotate-words": CubeRotateWords,
  "curved-text": CurvedText,
  "decrypt-text": DecryptText,
  "flip-text3-d": FlipText3D,
  "focus-blur-text": FocusBlurText,
  "glitch-text": GlitchText,
  "gradient-stroke-text": GradientStrokeText,
  "gradient-text": GradientText,
  "handwriting-signature": HandwritingSignature,
  "highlight-sweep-text": HighlightSweepText,
  "highlighter-text": HighlighterText,
  "kbd-shortcuts": KbdShortcuts,
  "kinetic-letter-wave": KineticLetterWave,
  "kinetic-marquee": KineticMarquee,
  "line-shadow-text": LineShadowText,
  "masked-line-reveal": MaskedLineReveal,
  "morphing-text": MorphingText,
  "number-ticker": NumberTicker,
  "outline-fill-text": OutlineFillText,
  "rainbow-underline-text": RainbowUnderlineText,
  "shadow-stack-text": ShadowStackText,
  "sparkles-text": SparklesText,
  "spinning-text": SpinningText,
  "split-flap-text": SplitFlapText,
  "strike-replace-text": StrikeReplaceText,
  "text-mask-reveal": TextMaskReveal,
  "text-rotate": TextRotate,
  "typing-animation": TypingAnimation,
  "variable-weight-text": VariableWeightText,
  "wavy-text": WavyText,
  "word-reveal": WordReveal,
  "airplane-mode-toggle": AirplaneModeToggle,
  "animated-theme-toggler": AnimatedThemeToggler,
  "async-switch": AsyncSwitch,
  "bell-mute-toggle": BellMuteToggle,
  "currency-toggle": CurrencyToggle,
  "follow-toggle-button": FollowToggleButton,
  "hamburger-swap": HamburgerSwap,
  "icon-knob-switch": IconKnobSwitch,
  "liquid-fill-switch": LiquidFillSwitch,
  "lock-unlock-toggle": LockUnlockToggle,
  "media-device-toggles": MediaDeviceToggles,
  "morph-check-switch": MorphCheckSwitch,
  "neumorphic-switch": NeumorphicSwitch,
  "on-off-label-switch": OnOffLabelSwitch,
  "password-visibility-toggle": PasswordVisibilityToggle,
  "play-pause-swap": PlayPauseSwap,
  "settings-switch-list": SettingsSwitchList,
  "stretchy-switch": StretchySwitch,
  "switch-card": SwitchCard,
  "switch-sizes": SwitchSizes,
  "text-toggle-group": TextToggleGroup,
  "theme-controller-radios": ThemeControllerRadios,
  "theme-switch": ThemeSwitch,
  "tri-state-toggle": TriStateToggle,
  "view-mode-toggle": ViewModeToggle,
  "avatar-stack-tooltip": AvatarStackTooltip,
  "bouncy-tooltip": BouncyTooltip,
  "color-tooltip-variants": ColorTooltipVariants,
  "copy-tooltip": CopyTooltip,
  "delayed-tooltip": DelayedTooltip,
  "dimensions-popover": DimensionsPopover,
  "disabled-reason-tooltip": DisabledReasonTooltip,
  "follow-cursor-tooltip": FollowCursorTooltip,
  "glossary-tooltip": GlossaryTooltip,
  "hover-card-tooltip": HoverCardTooltip,
  "image-hotspots": ImageHotspots,
  "info-icon-tooltip": InfoIconTooltip,
  "link-preview-tooltip": LinkPreviewTooltip,
  "onboarding-tour": OnboardingTour,
  "overflow-tags-popover": OverflowTagsPopover,
  "placement-tooltips": PlacementTooltips,
  "popconfirm-delete": PopconfirmDelete,
  "reaction-tooltip": ReactionTooltip,
  "shared-cursor-tooltip": SharedCursorTooltip,
  "shortcuts-help-popover": ShortcutsHelpPopover,
  "slider-value-tooltip": SliderValueTooltip,
  "status-dot-tooltip": StatusDotTooltip,
  "stepper-tooltips": StepperTooltips,
  "toast-stack": ToastStack,
  "toggletip": Toggletip,
  "toolbar-tooltips": ToolbarTooltips,
  "truncated-text-tooltip": TruncatedTextTooltip,
  "validation-popover": ValidationPopover,
};
