// Generated by scripts/sync-registry.mjs. Do not edit by hand.
import type { ComponentType } from 'react';
import { AgentTrace } from './ai-chat/AgentTrace';
import { AttachmentComposer } from './ai-chat/AttachmentComposer';
import { ChatHistoryList } from './ai-chat/ChatHistoryList';
import { ChatThread } from './ai-chat/ChatThread';
import { CodeAnswer } from './ai-chat/CodeAnswer';
import { ContextMeter } from './ai-chat/ContextMeter';
import { ImageGeneration } from './ai-chat/ImageGeneration';
import { MessageActions } from './ai-chat/MessageActions';
import { ModelSelector } from './ai-chat/ModelSelector';
import { PromptInputBar } from './ai-chat/PromptInputBar';
import { ResponseVariants } from './ai-chat/ResponseVariants';
import { SlashCommandMenu } from './ai-chat/SlashCommandMenu';
import { SourcesAnswer } from './ai-chat/SourcesAnswer';
import { StreamingMessage } from './ai-chat/StreamingMessage';
import { SuggestedPrompts } from './ai-chat/SuggestedPrompts';
import { SupportWidget } from './ai-chat/SupportWidget';
import { ThinkingAccordion } from './ai-chat/ThinkingAccordion';
import { TypingIndicator } from './ai-chat/TypingIndicator';
import { VoiceOrb } from './ai-chat/VoiceOrb';
import { BugTriageBoard } from './boards/BugTriageBoard';
import { ContentCalendar } from './boards/ContentCalendar';
import { DragDropKanban } from './boards/DragDropKanban';
import { GanttTimeline } from './boards/GanttTimeline';
import { GroupedIssueList } from './boards/GroupedIssueList';
import { HiringPipeline } from './boards/HiringPipeline';
import { InlineAddBoard } from './boards/InlineAddBoard';
import { IssueCardDetail } from './boards/IssueCardDetail';
import { MilestoneTracker } from './boards/MilestoneTracker';
import { MoodBoard } from './boards/MoodBoard';
import { NowNextLaterRoadmap } from './boards/NowNextLaterRoadmap';
import { OkrBoard } from './boards/OkrBoard';
import { RetroBoard } from './boards/RetroBoard';
import { SalesPipeline } from './boards/SalesPipeline';
import { StickyNotesWall } from './boards/StickyNotesWall';
import { SwimlaneBoard } from './boards/SwimlaneBoard';
import { WipLimitBoard } from './boards/WipLimitBoard';
import { BorderBeamButton } from './buttons/BorderBeamButton';
import { ButtonVariants } from './buttons/ButtonVariants';
import { CopyLinkButton } from './buttons/CopyLinkButton';
import { DownloadProgressButton } from './buttons/DownloadProgressButton';
import { ExpandIconButton } from './buttons/ExpandIconButton';
import { HoldToConfirmButton } from './buttons/HoldToConfirmButton';
import { LikeBurstButton } from './buttons/LikeBurstButton';
import { MagneticPullButton } from './buttons/MagneticPullButton';
import { NeonButton } from './buttons/NeonButton';
import { PushButton } from './buttons/PushButton';
import { RainbowButton } from './buttons/RainbowButton';
import { RippleButton } from './buttons/RippleButton';
import { ShimmerButton } from './buttons/ShimmerButton';
import { SlideArrowButton } from './buttons/SlideArrowButton';
import { SplitButton } from './buttons/SplitButton';
import { BentoFeatures } from './cards/BentoFeatures';
import { SpotlightCard } from './cards/SpotlightCard';
import { StatCard } from './cards/StatCard';
import { BulletChart } from './charts/BulletChart';
import { CandlestickChart } from './charts/CandlestickChart';
import { ForecastLineChart } from './charts/ForecastLineChart';
import { GroupedBarChart } from './charts/GroupedBarChart';
import { PolarAreaChart } from './charts/PolarAreaChart';
import { RadarChart } from './charts/RadarChart';
import { ScatterPlot } from './charts/ScatterPlot';
import { StackedAreaChart } from './charts/StackedAreaChart';
import { TreemapChart } from './charts/TreemapChart';
import { WaterfallChart } from './charts/WaterfallChart';
import { AnimatedChecklist } from './checkboxes/AnimatedChecklist';
import { CheckboxCards } from './checkboxes/CheckboxCards';
import { CircleCheckbox } from './checkboxes/CircleCheckbox';
import { ColorSwatchCheckboxes } from './checkboxes/ColorSwatchCheckboxes';
import { HeartCheckbox } from './checkboxes/HeartCheckbox';
import { IndeterminateTree } from './checkboxes/IndeterminateTree';
import { InterestChips } from './checkboxes/InterestChips';
import { JellyCheckbox } from './checkboxes/JellyCheckbox';
import { NeonCheckbox } from './checkboxes/NeonCheckbox';
import { PermissionsMatrix } from './checkboxes/PermissionsMatrix';
import { TermsConsentForm } from './checkboxes/TermsConsentForm';
import { WeekdayPicker } from './checkboxes/WeekdayPicker';
import { BookDemoCta } from './cta/BookDemoCta';
import { CommunityJoinCta } from './cta/CommunityJoinCta';
import { GradientShapesCta } from './cta/GradientShapesCta';
import { InlineBannerCta } from './cta/InlineBannerCta';
import { InlineNewsletterCta } from './cta/InlineNewsletterCta';
import { SplitImageCta } from './cta/SplitImageCta';
import { SpotlightCta } from './cta/SpotlightCta';
import { StatsCta } from './cta/StatsCta';
import { TestimonialCta } from './cta/TestimonialCta';
import { TrialChecklistCta } from './cta/TrialChecklistCta';
import { ActivityFeed } from './dashboard/ActivityFeed';
import { BillingSummary } from './dashboard/BillingSummary';
import { ContributionHeatmap } from './dashboard/ContributionHeatmap';
import { ConversionBreakdown } from './dashboard/ConversionBreakdown';
import { DarkMetricPanel } from './dashboard/DarkMetricPanel';
import { GoalGauge } from './dashboard/GoalGauge';
import { KpiGrid } from './dashboard/KpiGrid';
import { ProjectProgressList } from './dashboard/ProjectProgressList';
import { RealtimeVisitors } from './dashboard/RealtimeVisitors';
import { RecentSales } from './dashboard/RecentSales';
import { RevenueOverview } from './dashboard/RevenueOverview';
import { ServiceUptime } from './dashboard/ServiceUptime';
import { StorageUsage } from './dashboard/StorageUsage';
import { TasksWidget } from './dashboard/TasksWidget';
import { TeamWorkload } from './dashboard/TeamWorkload';
import { TopCountries } from './dashboard/TopCountries';
import { UpcomingEvents } from './dashboard/UpcomingEvents';
import { WelcomeBanner } from './dashboard/WelcomeBanner';
import { AccordionSitemapFooter } from './footer/AccordionSitemapFooter';
import { AppDownloadFooter } from './footer/AppDownloadFooter';
import { BackToTopFooter } from './footer/BackToTopFooter';
import { ColumnsNewsletterFooter } from './footer/ColumnsNewsletterFooter';
import { CommunityFooter } from './footer/CommunityFooter';
import { ContactInfoFooter } from './footer/ContactInfoFooter';
import { CtaBandFooter } from './footer/CtaBandFooter';
import { FloatingCardFooter } from './footer/FloatingCardFooter';
import { LegalBarFooter } from './footer/LegalBarFooter';
import { MagazineFooter } from './footer/MagazineFooter';
import { MinimalCenteredFooter } from './footer/MinimalCenteredFooter';
import { OfficesFooter } from './footer/OfficesFooter';
import { PartnersFooter } from './footer/PartnersFooter';
import { PreferencesFooter } from './footer/PreferencesFooter';
import { StatusFooter } from './footer/StatusFooter';
import { WaveFooter } from './footer/WaveFooter';
import { WordmarkFooter } from './footer/WordmarkFooter';
import { AutocompleteInput } from './forms/AutocompleteInput';
import { DualRangeSlider } from './forms/DualRangeSlider';
import { FeedbackForm } from './forms/FeedbackForm';
import { FileDropzone } from './forms/FileDropzone';
import { FloatingLabelInput } from './forms/FloatingLabelInput';
import { ForgotPassword } from './forms/ForgotPassword';
import { InlineDatePicker } from './forms/InlineDatePicker';
import { MultiSelectCombobox } from './forms/MultiSelectCombobox';
import { OtpInput } from './forms/OtpInput';
import { PasswordStrength } from './forms/PasswordStrength';
import { PhoneInput } from './forms/PhoneInput';
import { SignInForm } from './forms/SignInForm';
import { StarRatingInput } from './forms/StarRatingInput';
import { TagInput } from './forms/TagInput';
import { ValidatedContactForm } from './forms/ValidatedContactForm';
import { WizardForm } from './forms/WizardForm';
import { AuroraBlobHero } from './hero/AuroraBlobHero';
import { BeamSpotlightHero } from './hero/BeamSpotlightHero';
import { CountdownHero } from './hero/CountdownHero';
import { EditorialHero } from './hero/EditorialHero';
import { FloatingCardsHero } from './hero/FloatingCardsHero';
import { GridGlowHero } from './hero/GridGlowHero';
import { LogoCloudHero } from './hero/LogoCloudHero';
import { MetricsHero } from './hero/MetricsHero';
import { PhoneMockupHero } from './hero/PhoneMockupHero';
import { SearchHero } from './hero/SearchHero';
import { SplitMockupHero } from './hero/SplitMockupHero';
import { TerminalHero } from './hero/TerminalHero';
import { TypewriterHero } from './hero/TypewriterHero';
import { VideoPreviewHero } from './hero/VideoPreviewHero';
import { WaitlistHero } from './hero/WaitlistHero';
import { BouncingDots } from './loader/BouncingDots';
import { CircularProgress } from './loader/CircularProgress';
import { ClockLoader } from './loader/ClockLoader';
import { CubeGrid } from './loader/CubeGrid';
import { EqualizerBars } from './loader/EqualizerBars';
import { FlippingSquare } from './loader/FlippingSquare';
import { GradientRingSpinner } from './loader/GradientRingSpinner';
import { HourglassLoader } from './loader/HourglassLoader';
import { IndeterminateBar } from './loader/IndeterminateBar';
import { InfinityLoader } from './loader/InfinityLoader';
import { LetterWave } from './loader/LetterWave';
import { LoadingButton } from './loader/LoadingButton';
import { OrbitDotsLoader } from './loader/OrbitDotsLoader';
import { PulseRings } from './loader/PulseRings';
import { SegmentSpinner } from './loader/SegmentSpinner';
import { SkeletonCard } from './loader/SkeletonCard';
import { SkeletonList } from './loader/SkeletonList';
import { StepsLoader } from './loader/StepsLoader';
import { ActionSheet } from './menu/ActionSheet';
import { BreadcrumbOverflowMenu } from './menu/BreadcrumbOverflowMenu';
import { CommandPalette } from './menu/CommandPalette';
import { ContextMenu } from './menu/ContextMenu';
import { IconSelectMenu } from './menu/IconSelectMenu';
import { ReactionPickerMenu } from './menu/ReactionPickerMenu';
import { RowActionsMenu } from './menu/RowActionsMenu';
import { SortFilterMenu } from './menu/SortFilterMenu';
import { SpeedDialMenu } from './menu/SpeedDialMenu';
import { SubmenuDropdown } from './menu/SubmenuDropdown';
import { AnnouncementNavbar } from './navbar/AnnouncementNavbar';
import { AppHeaderNavbar } from './navbar/AppHeaderNavbar';
import { BottomTabBar } from './navbar/BottomTabBar';
import { CenteredLinksNavbar } from './navbar/CenteredLinksNavbar';
import { CheckoutStepsNavbar } from './navbar/CheckoutStepsNavbar';
import { DarkMinimalNavbar } from './navbar/DarkMinimalNavbar';
import { DocsNavbar } from './navbar/DocsNavbar';
import { GlassPillNavbar } from './navbar/GlassPillNavbar';
import { GradientBorderNavbar } from './navbar/GradientBorderNavbar';
import { LanguageNavbar } from './navbar/LanguageNavbar';
import { MegaMenuNavbar } from './navbar/MegaMenuNavbar';
import { NotificationNavbar } from './navbar/NotificationNavbar';
import { ReadingProgressNavbar } from './navbar/ReadingProgressNavbar';
import { SegmentedNavbar } from './navbar/SegmentedNavbar';
import { ShopNavbar } from './navbar/ShopNavbar';
import { SplitLogoNavbar } from './navbar/SplitLogoNavbar';
import { UnderlineTabsNavbar } from './navbar/UnderlineTabsNavbar';
import { UserMenuNavbar } from './navbar/UserMenuNavbar';
import { CouponCheckout } from './pricing/CouponCheckout';
import { CreditPacks } from './pricing/CreditPacks';
import { CurrencyPricing } from './pricing/CurrencyPricing';
import { EditorialPriceList } from './pricing/EditorialPriceList';
import { EnterpriseContactCard } from './pricing/EnterpriseContactCard';
import { GlowPlanCards } from './pricing/GlowPlanCards';
import { PlanRadioSelector } from './pricing/PlanRadioSelector';
import { PricingToggle } from './pricing/PricingToggle';
import { PricingWithFaq } from './pricing/PricingWithFaq';
import { RegionalDiscount } from './pricing/RegionalDiscount';
import { SeatSliderPricing } from './pricing/SeatSliderPricing';
import { SeatStepper } from './pricing/SeatStepper';
import { SinglePlanCard } from './pricing/SinglePlanCard';
import { SquishyPricing } from './pricing/SquishyPricing';
import { ThreeTierPricing } from './pricing/ThreeTierPricing';
import { TrialTimeline } from './pricing/TrialTimeline';
import { UpgradePrompt } from './pricing/UpgradePrompt';
import { UsageCalculator } from './pricing/UsageCalculator';
import { AuroraCurtain } from './shaders/AuroraCurtain';
import { BackgroundPaths } from './shaders/BackgroundPaths';
import { ClickRipple } from './shaders/ClickRipple';
import { ConicHalo } from './shaders/ConicHalo';
import { DitherGradient } from './shaders/DitherGradient';
import { DotWave } from './shaders/DotWave';
import { GlowLines } from './shaders/GlowLines';
import { GooeyBlobs } from './shaders/GooeyBlobs';
import { InfiniteGrid } from './shaders/InfiniteGrid';
import { LiquidChrome } from './shaders/LiquidChrome';
import { MatrixRain } from './shaders/MatrixRain';
import { MeshGradient } from './shaders/MeshGradient';
import { NetworkParticles } from './shaders/NetworkParticles';
import { NoiseGrain } from './shaders/NoiseGrain';
import { OrbitRings } from './shaders/OrbitRings';
import { SiriWave } from './shaders/SiriWave';
import { SpotlightGrid } from './shaders/SpotlightGrid';
import { Starfield } from './shaders/Starfield';
import { TopographyLines } from './shaders/TopographyLines';
import { ChannelsSidebar } from './sidebar/ChannelsSidebar';
import { CollapsibleIconSidebar } from './sidebar/CollapsibleIconSidebar';
import { CourseProgressSidebar } from './sidebar/CourseProgressSidebar';
import { DualPaneSidebar } from './sidebar/DualPaneSidebar';
import { FilterSidebar } from './sidebar/FilterSidebar';
import { FolderTreeSidebar } from './sidebar/FolderTreeSidebar';
import { GlassDockSidebar } from './sidebar/GlassDockSidebar';
import { InboxSidebar } from './sidebar/InboxSidebar';
import { MobileDrawerSidebar } from './sidebar/MobileDrawerSidebar';
import { MusicLibrarySidebar } from './sidebar/MusicLibrarySidebar';
import { NestedTreeSidebar } from './sidebar/NestedTreeSidebar';
import { ProjectsSidebar } from './sidebar/ProjectsSidebar';
import { SearchableSidebar } from './sidebar/SearchableSidebar';
import { SettingsSidebar } from './sidebar/SettingsSidebar';
import { TocSidebar } from './sidebar/TocSidebar';
import { UpgradeCardSidebar } from './sidebar/UpgradeCardSidebar';
import { WorkspaceSwitcherSidebar } from './sidebar/WorkspaceSwitcherSidebar';
import { DensityToggleTable } from './tables/DensityToggleTable';
import { EditableCellTable } from './tables/EditableCellTable';
import { EmptyStateTable } from './tables/EmptyStateTable';
import { ExpandableRowsTable } from './tables/ExpandableRowsTable';
import { FeatureComparisonTable } from './tables/FeatureComparisonTable';
import { FileListTable } from './tables/FileListTable';
import { FilterTabsTable } from './tables/FilterTabsTable';
import { HeatmapTable } from './tables/HeatmapTable';
import { InvoiceTable } from './tables/InvoiceTable';
import { LeaderboardTable } from './tables/LeaderboardTable';
import { OrderTrackingTable } from './tables/OrderTrackingTable';
import { PaginatedTable } from './tables/PaginatedTable';
import { ResponsiveCardTable } from './tables/ResponsiveCardTable';
import { SelectableTable } from './tables/SelectableTable';
import { SortableTable } from './tables/SortableTable';
import { SpecsTable } from './tables/SpecsTable';
import { StickyHeaderTable } from './tables/StickyHeaderTable';
import { TeamStatusTable } from './tables/TeamStatusTable';
import { TransactionsTable } from './tables/TransactionsTable';
import { AvatarPickerTestimonial } from './testimonials/AvatarPickerTestimonial';
import { CaseStudyCard } from './testimonials/CaseStudyCard';
import { CompactTestimonialList } from './testimonials/CompactTestimonialList';
import { GradientBorderQuote } from './testimonials/GradientBorderQuote';
import { LogoMetricTestimonial } from './testimonials/LogoMetricTestimonial';
import { MarqueeTestimonials } from './testimonials/MarqueeTestimonials';
import { QuoteSpotlight } from './testimonials/QuoteSpotlight';
import { RatingStrip } from './testimonials/RatingStrip';
import { RatingSummary } from './testimonials/RatingSummary';
import { ReviewWithReply } from './testimonials/ReviewWithReply';
import { RoleTabsTestimonials } from './testimonials/RoleTabsTestimonials';
import { SocialPostCards } from './testimonials/SocialPostCards';
import { StackedTestimonials } from './testimonials/StackedTestimonials';
import { TestimonialCarousel } from './testimonials/TestimonialCarousel';
import { TestimonialWall } from './testimonials/TestimonialWall';
import { TiltTestimonialCard } from './testimonials/TiltTestimonialCard';
import { VideoTestimonial } from './testimonials/VideoTestimonial';
import { AnimatedUnderlines } from './text/AnimatedUnderlines';
import { AuroraText } from './text/AuroraText';
import { BounceHoverText } from './text/BounceHoverText';
import { CurvedText } from './text/CurvedText';
import { DecryptText } from './text/DecryptText';
import { GlitchText } from './text/GlitchText';
import { GradientText } from './text/GradientText';
import { HandwritingSignature } from './text/HandwritingSignature';
import { HighlighterText } from './text/HighlighterText';
import { KbdShortcuts } from './text/KbdShortcuts';
import { KineticMarquee } from './text/KineticMarquee';
import { NumberTicker } from './text/NumberTicker';
import { OutlineFillText } from './text/OutlineFillText';
import { SparklesText } from './text/SparklesText';
import { SplitFlapText } from './text/SplitFlapText';
import { StrikeReplaceText } from './text/StrikeReplaceText';
import { TextRotate } from './text/TextRotate';
import { WordReveal } from './text/WordReveal';
import { IconKnobSwitch } from './toggle/IconKnobSwitch';
import { MorphCheckSwitch } from './toggle/MorphCheckSwitch';
import { NeumorphicSwitch } from './toggle/NeumorphicSwitch';
import { OnOffLabelSwitch } from './toggle/OnOffLabelSwitch';
import { SettingsSwitchList } from './toggle/SettingsSwitchList';
import { StretchySwitch } from './toggle/StretchySwitch';
import { TextToggleGroup } from './toggle/TextToggleGroup';
import { ThemeSwitch } from './toggle/ThemeSwitch';
import { AvatarStackTooltip } from './tooltips/AvatarStackTooltip';
import { BouncyTooltip } from './tooltips/BouncyTooltip';
import { DelayedTooltip } from './tooltips/DelayedTooltip';
import { FollowCursorTooltip } from './tooltips/FollowCursorTooltip';
import { GlossaryTooltip } from './tooltips/GlossaryTooltip';
import { HoverCardTooltip } from './tooltips/HoverCardTooltip';
import { InfoIconTooltip } from './tooltips/InfoIconTooltip';
import { PlacementTooltips } from './tooltips/PlacementTooltips';
import { SliderValueTooltip } from './tooltips/SliderValueTooltip';
import { StatusDotTooltip } from './tooltips/StatusDotTooltip';
import { Toggletip } from './tooltips/Toggletip';
import { TruncatedTextTooltip } from './tooltips/TruncatedTextTooltip';

/** Registry components render from their own file and support light and dark mode. */
export const registryComponents: Record<string, ComponentType> = {
  "agent-trace": AgentTrace,
  "attachment-composer": AttachmentComposer,
  "chat-history-list": ChatHistoryList,
  "chat-thread": ChatThread,
  "code-answer": CodeAnswer,
  "context-meter": ContextMeter,
  "image-generation": ImageGeneration,
  "message-actions": MessageActions,
  "model-selector": ModelSelector,
  "prompt-input-bar": PromptInputBar,
  "response-variants": ResponseVariants,
  "slash-command-menu": SlashCommandMenu,
  "sources-answer": SourcesAnswer,
  "streaming-message": StreamingMessage,
  "suggested-prompts": SuggestedPrompts,
  "support-widget": SupportWidget,
  "thinking-accordion": ThinkingAccordion,
  "typing-indicator": TypingIndicator,
  "voice-orb": VoiceOrb,
  "bug-triage-board": BugTriageBoard,
  "content-calendar": ContentCalendar,
  "drag-drop-kanban": DragDropKanban,
  "gantt-timeline": GanttTimeline,
  "grouped-issue-list": GroupedIssueList,
  "hiring-pipeline": HiringPipeline,
  "inline-add-board": InlineAddBoard,
  "issue-card-detail": IssueCardDetail,
  "milestone-tracker": MilestoneTracker,
  "mood-board": MoodBoard,
  "now-next-later-roadmap": NowNextLaterRoadmap,
  "okr-board": OkrBoard,
  "retro-board": RetroBoard,
  "sales-pipeline": SalesPipeline,
  "sticky-notes-wall": StickyNotesWall,
  "swimlane-board": SwimlaneBoard,
  "wip-limit-board": WipLimitBoard,
  "border-beam-button": BorderBeamButton,
  "button-variants": ButtonVariants,
  "copy-link-button": CopyLinkButton,
  "download-progress-button": DownloadProgressButton,
  "expand-icon-button": ExpandIconButton,
  "hold-to-confirm-button": HoldToConfirmButton,
  "like-burst-button": LikeBurstButton,
  "magnetic-pull-button": MagneticPullButton,
  "neon-button": NeonButton,
  "push-button": PushButton,
  "rainbow-button": RainbowButton,
  "ripple-button": RippleButton,
  "shimmer-button": ShimmerButton,
  "slide-arrow-button": SlideArrowButton,
  "split-button": SplitButton,
  "bento-features": BentoFeatures,
  "spotlight-card": SpotlightCard,
  "stat-card": StatCard,
  "bullet-chart": BulletChart,
  "candlestick-chart": CandlestickChart,
  "forecast-line-chart": ForecastLineChart,
  "grouped-bar-chart": GroupedBarChart,
  "polar-area-chart": PolarAreaChart,
  "radar-chart": RadarChart,
  "scatter-plot": ScatterPlot,
  "stacked-area-chart": StackedAreaChart,
  "treemap-chart": TreemapChart,
  "waterfall-chart": WaterfallChart,
  "animated-checklist": AnimatedChecklist,
  "checkbox-cards": CheckboxCards,
  "circle-checkbox": CircleCheckbox,
  "color-swatch-checkboxes": ColorSwatchCheckboxes,
  "heart-checkbox": HeartCheckbox,
  "indeterminate-tree": IndeterminateTree,
  "interest-chips": InterestChips,
  "jelly-checkbox": JellyCheckbox,
  "neon-checkbox": NeonCheckbox,
  "permissions-matrix": PermissionsMatrix,
  "terms-consent-form": TermsConsentForm,
  "weekday-picker": WeekdayPicker,
  "book-demo-cta": BookDemoCta,
  "community-join-cta": CommunityJoinCta,
  "gradient-shapes-cta": GradientShapesCta,
  "inline-banner-cta": InlineBannerCta,
  "inline-newsletter-cta": InlineNewsletterCta,
  "split-image-cta": SplitImageCta,
  "spotlight-cta": SpotlightCta,
  "stats-cta": StatsCta,
  "testimonial-cta": TestimonialCta,
  "trial-checklist-cta": TrialChecklistCta,
  "activity-feed": ActivityFeed,
  "billing-summary": BillingSummary,
  "contribution-heatmap": ContributionHeatmap,
  "conversion-breakdown": ConversionBreakdown,
  "dark-metric-panel": DarkMetricPanel,
  "goal-gauge": GoalGauge,
  "kpi-grid": KpiGrid,
  "project-progress-list": ProjectProgressList,
  "realtime-visitors": RealtimeVisitors,
  "recent-sales": RecentSales,
  "revenue-overview": RevenueOverview,
  "service-uptime": ServiceUptime,
  "storage-usage": StorageUsage,
  "tasks-widget": TasksWidget,
  "team-workload": TeamWorkload,
  "top-countries": TopCountries,
  "upcoming-events": UpcomingEvents,
  "welcome-banner": WelcomeBanner,
  "accordion-sitemap-footer": AccordionSitemapFooter,
  "app-download-footer": AppDownloadFooter,
  "back-to-top-footer": BackToTopFooter,
  "columns-newsletter-footer": ColumnsNewsletterFooter,
  "community-footer": CommunityFooter,
  "contact-info-footer": ContactInfoFooter,
  "cta-band-footer": CtaBandFooter,
  "floating-card-footer": FloatingCardFooter,
  "legal-bar-footer": LegalBarFooter,
  "magazine-footer": MagazineFooter,
  "minimal-centered-footer": MinimalCenteredFooter,
  "offices-footer": OfficesFooter,
  "partners-footer": PartnersFooter,
  "preferences-footer": PreferencesFooter,
  "status-footer": StatusFooter,
  "wave-footer": WaveFooter,
  "wordmark-footer": WordmarkFooter,
  "autocomplete-input": AutocompleteInput,
  "dual-range-slider": DualRangeSlider,
  "feedback-form": FeedbackForm,
  "file-dropzone": FileDropzone,
  "floating-label-input": FloatingLabelInput,
  "forgot-password": ForgotPassword,
  "inline-date-picker": InlineDatePicker,
  "multi-select-combobox": MultiSelectCombobox,
  "otp-input": OtpInput,
  "password-strength": PasswordStrength,
  "phone-input": PhoneInput,
  "sign-in-form": SignInForm,
  "star-rating-input": StarRatingInput,
  "tag-input": TagInput,
  "validated-contact-form": ValidatedContactForm,
  "wizard-form": WizardForm,
  "aurora-blob-hero": AuroraBlobHero,
  "beam-spotlight-hero": BeamSpotlightHero,
  "countdown-hero": CountdownHero,
  "editorial-hero": EditorialHero,
  "floating-cards-hero": FloatingCardsHero,
  "grid-glow-hero": GridGlowHero,
  "logo-cloud-hero": LogoCloudHero,
  "metrics-hero": MetricsHero,
  "phone-mockup-hero": PhoneMockupHero,
  "search-hero": SearchHero,
  "split-mockup-hero": SplitMockupHero,
  "terminal-hero": TerminalHero,
  "typewriter-hero": TypewriterHero,
  "video-preview-hero": VideoPreviewHero,
  "waitlist-hero": WaitlistHero,
  "bouncing-dots": BouncingDots,
  "circular-progress": CircularProgress,
  "clock-loader": ClockLoader,
  "cube-grid": CubeGrid,
  "equalizer-bars": EqualizerBars,
  "flipping-square": FlippingSquare,
  "gradient-ring-spinner": GradientRingSpinner,
  "hourglass-loader": HourglassLoader,
  "indeterminate-bar": IndeterminateBar,
  "infinity-loader": InfinityLoader,
  "letter-wave": LetterWave,
  "loading-button": LoadingButton,
  "orbit-dots-loader": OrbitDotsLoader,
  "pulse-rings": PulseRings,
  "segment-spinner": SegmentSpinner,
  "skeleton-card": SkeletonCard,
  "skeleton-list": SkeletonList,
  "steps-loader": StepsLoader,
  "action-sheet": ActionSheet,
  "breadcrumb-overflow-menu": BreadcrumbOverflowMenu,
  "command-palette": CommandPalette,
  "context-menu": ContextMenu,
  "icon-select-menu": IconSelectMenu,
  "reaction-picker-menu": ReactionPickerMenu,
  "row-actions-menu": RowActionsMenu,
  "sort-filter-menu": SortFilterMenu,
  "speed-dial-menu": SpeedDialMenu,
  "submenu-dropdown": SubmenuDropdown,
  "announcement-navbar": AnnouncementNavbar,
  "app-header-navbar": AppHeaderNavbar,
  "bottom-tab-bar": BottomTabBar,
  "centered-links-navbar": CenteredLinksNavbar,
  "checkout-steps-navbar": CheckoutStepsNavbar,
  "dark-minimal-navbar": DarkMinimalNavbar,
  "docs-navbar": DocsNavbar,
  "glass-pill-navbar": GlassPillNavbar,
  "gradient-border-navbar": GradientBorderNavbar,
  "language-navbar": LanguageNavbar,
  "mega-menu-navbar": MegaMenuNavbar,
  "notification-navbar": NotificationNavbar,
  "reading-progress-navbar": ReadingProgressNavbar,
  "segmented-navbar": SegmentedNavbar,
  "shop-navbar": ShopNavbar,
  "split-logo-navbar": SplitLogoNavbar,
  "underline-tabs-navbar": UnderlineTabsNavbar,
  "user-menu-navbar": UserMenuNavbar,
  "coupon-checkout": CouponCheckout,
  "credit-packs": CreditPacks,
  "currency-pricing": CurrencyPricing,
  "editorial-price-list": EditorialPriceList,
  "enterprise-contact-card": EnterpriseContactCard,
  "glow-plan-cards": GlowPlanCards,
  "plan-radio-selector": PlanRadioSelector,
  "pricing-toggle": PricingToggle,
  "pricing-with-faq": PricingWithFaq,
  "regional-discount": RegionalDiscount,
  "seat-slider-pricing": SeatSliderPricing,
  "seat-stepper": SeatStepper,
  "single-plan-card": SinglePlanCard,
  "squishy-pricing": SquishyPricing,
  "three-tier-pricing": ThreeTierPricing,
  "trial-timeline": TrialTimeline,
  "upgrade-prompt": UpgradePrompt,
  "usage-calculator": UsageCalculator,
  "aurora-curtain": AuroraCurtain,
  "background-paths": BackgroundPaths,
  "click-ripple": ClickRipple,
  "conic-halo": ConicHalo,
  "dither-gradient": DitherGradient,
  "dot-wave": DotWave,
  "glow-lines": GlowLines,
  "gooey-blobs": GooeyBlobs,
  "infinite-grid": InfiniteGrid,
  "liquid-chrome": LiquidChrome,
  "matrix-rain": MatrixRain,
  "mesh-gradient": MeshGradient,
  "network-particles": NetworkParticles,
  "noise-grain": NoiseGrain,
  "orbit-rings": OrbitRings,
  "siri-wave": SiriWave,
  "spotlight-grid": SpotlightGrid,
  "starfield": Starfield,
  "topography-lines": TopographyLines,
  "channels-sidebar": ChannelsSidebar,
  "collapsible-icon-sidebar": CollapsibleIconSidebar,
  "course-progress-sidebar": CourseProgressSidebar,
  "dual-pane-sidebar": DualPaneSidebar,
  "filter-sidebar": FilterSidebar,
  "folder-tree-sidebar": FolderTreeSidebar,
  "glass-dock-sidebar": GlassDockSidebar,
  "inbox-sidebar": InboxSidebar,
  "mobile-drawer-sidebar": MobileDrawerSidebar,
  "music-library-sidebar": MusicLibrarySidebar,
  "nested-tree-sidebar": NestedTreeSidebar,
  "projects-sidebar": ProjectsSidebar,
  "searchable-sidebar": SearchableSidebar,
  "settings-sidebar": SettingsSidebar,
  "toc-sidebar": TocSidebar,
  "upgrade-card-sidebar": UpgradeCardSidebar,
  "workspace-switcher-sidebar": WorkspaceSwitcherSidebar,
  "density-toggle-table": DensityToggleTable,
  "editable-cell-table": EditableCellTable,
  "empty-state-table": EmptyStateTable,
  "expandable-rows-table": ExpandableRowsTable,
  "feature-comparison-table": FeatureComparisonTable,
  "file-list-table": FileListTable,
  "filter-tabs-table": FilterTabsTable,
  "heatmap-table": HeatmapTable,
  "invoice-table": InvoiceTable,
  "leaderboard-table": LeaderboardTable,
  "order-tracking-table": OrderTrackingTable,
  "paginated-table": PaginatedTable,
  "responsive-card-table": ResponsiveCardTable,
  "selectable-table": SelectableTable,
  "sortable-table": SortableTable,
  "specs-table": SpecsTable,
  "sticky-header-table": StickyHeaderTable,
  "team-status-table": TeamStatusTable,
  "transactions-table": TransactionsTable,
  "avatar-picker-testimonial": AvatarPickerTestimonial,
  "case-study-card": CaseStudyCard,
  "compact-testimonial-list": CompactTestimonialList,
  "gradient-border-quote": GradientBorderQuote,
  "logo-metric-testimonial": LogoMetricTestimonial,
  "marquee-testimonials": MarqueeTestimonials,
  "quote-spotlight": QuoteSpotlight,
  "rating-strip": RatingStrip,
  "rating-summary": RatingSummary,
  "review-with-reply": ReviewWithReply,
  "role-tabs-testimonials": RoleTabsTestimonials,
  "social-post-cards": SocialPostCards,
  "stacked-testimonials": StackedTestimonials,
  "testimonial-carousel": TestimonialCarousel,
  "testimonial-wall": TestimonialWall,
  "tilt-testimonial-card": TiltTestimonialCard,
  "video-testimonial": VideoTestimonial,
  "animated-underlines": AnimatedUnderlines,
  "aurora-text": AuroraText,
  "bounce-hover-text": BounceHoverText,
  "curved-text": CurvedText,
  "decrypt-text": DecryptText,
  "glitch-text": GlitchText,
  "gradient-text": GradientText,
  "handwriting-signature": HandwritingSignature,
  "highlighter-text": HighlighterText,
  "kbd-shortcuts": KbdShortcuts,
  "kinetic-marquee": KineticMarquee,
  "number-ticker": NumberTicker,
  "outline-fill-text": OutlineFillText,
  "sparkles-text": SparklesText,
  "split-flap-text": SplitFlapText,
  "strike-replace-text": StrikeReplaceText,
  "text-rotate": TextRotate,
  "word-reveal": WordReveal,
  "icon-knob-switch": IconKnobSwitch,
  "morph-check-switch": MorphCheckSwitch,
  "neumorphic-switch": NeumorphicSwitch,
  "on-off-label-switch": OnOffLabelSwitch,
  "settings-switch-list": SettingsSwitchList,
  "stretchy-switch": StretchySwitch,
  "text-toggle-group": TextToggleGroup,
  "theme-switch": ThemeSwitch,
  "avatar-stack-tooltip": AvatarStackTooltip,
  "bouncy-tooltip": BouncyTooltip,
  "delayed-tooltip": DelayedTooltip,
  "follow-cursor-tooltip": FollowCursorTooltip,
  "glossary-tooltip": GlossaryTooltip,
  "hover-card-tooltip": HoverCardTooltip,
  "info-icon-tooltip": InfoIconTooltip,
  "placement-tooltips": PlacementTooltips,
  "slider-value-tooltip": SliderValueTooltip,
  "status-dot-tooltip": StatusDotTooltip,
  "toggletip": Toggletip,
  "truncated-text-tooltip": TruncatedTextTooltip,
};
