/**
 * @registry
 * name: Application Tracker
 * category: Dashboard
 * style: Gradient
 * tags: recent
 * description: Suivi chronologique d'une candidature avec prochaine action et entretien.
 * prompt: Create a responsive job application tracker showing applied, reviewed, interview and decision stages, current status, next interview details and withdraw action.
 */
'use client';
import { CalendarClock, Check, Video } from 'lucide-react';import { useState } from 'react';
const stages=['Applied','Reviewed','Interview','Decision'];
export function ApplicationTracker(){const[withdrawn,setWithdrawn]=useState(false);return <section className="w-full max-w-full overflow-hidden rounded-3xl sm:max-w-2xl border border-zinc-200 bg-white p-5 shadow-xl dark:border-zinc-800 dark:bg-zinc-950 sm:p-7">{withdrawn?<div className="py-8 text-center"><p className="font-semibold text-zinc-900 dark:text-white">Application withdrawn</p><button onClick={()=>setWithdrawn(false)} className="mt-3 text-sm font-semibold text-blue-600">Restore demo</button></div>:<><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="grid size-11 place-items-center rounded-xl bg-blue-600 font-black text-white">N</div><div className="flex-1"><p className="text-xs font-semibold text-blue-600">Northstar Labs</p><h2 className="text-lg font-bold text-zinc-950 dark:text-white">Senior Product Designer</h2><p className="text-xs text-zinc-500">Application #NS-2048</p></div><span className="self-start rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700 dark:bg-amber-500/10 dark:text-amber-300">Interview stage</span></div><div className="mt-7 flex items-start">{stages.map((stage,index)=><div key={stage} className="flex flex-1 flex-col items-center text-center"><div className="flex w-full items-center"><span className={`h-0.5 flex-1 ${index===0?'bg-transparent':index<=2?'bg-blue-500':'bg-zinc-200 dark:bg-zinc-800'}`}/><span className={`grid size-7 shrink-0 place-items-center rounded-full text-xs ${index<=2?'bg-blue-600 text-white':'bg-zinc-100 text-zinc-400 dark:bg-zinc-900'}`}>{index<2?<Check size={13}/>:index+1}</span><span className={`h-0.5 flex-1 ${index<2?'bg-blue-500':'bg-zinc-200 dark:bg-zinc-800'}`}/></div><span className="mt-2 text-[10px] font-medium text-zinc-500 sm:text-xs">{stage}</span></div>)}</div><div className="mt-7 flex flex-col gap-4 rounded-2xl bg-gradient-to-r from-blue-600 to-violet-600 p-4 text-white sm:flex-row sm:items-center"><div className="grid size-10 place-items-center rounded-xl bg-white/15"><Video size={19}/></div><div className="flex-1"><p className="text-xs text-blue-100">Next step</p><p className="font-semibold">Portfolio interview</p><p className="mt-1 flex items-center gap-1 text-xs text-blue-100"><CalendarClock size={13}/>Thursday · 10:30 GMT</p></div><button className="rounded-xl bg-white px-4 py-2 text-xs font-bold text-blue-700">Join meeting</button></div><button onClick={()=>setWithdrawn(true)} className="mt-4 text-xs font-medium text-zinc-400 hover:text-rose-500">Withdraw application</button></>}</section>}
